### ISSUE TITLE
When you update a monitor, an exception can occur when the related adapter executes

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#2162]
**Describe the issue**
I was testing monitoring using Eclipse. I replaced the configuration of ibis4example by my own example configuration. That configuration defined a monitor and it had an adapter with which you could raise or clear the monitor. Initially, the adapter had no threshold and no period. Then I went to the console and updated the monitor to give it a non-zero period and a non-zero threshold. Then an exception occurred when I ran the adapter in test-a-pipeline.

**Reporter**
Martijn Dirkse

**To Reproduce**
1. Replace `Configuration.xml` of ibis4example with the configuration shown below.
2. Go to test-a-pipeline and run adapter `TestMonitoring` a few times.
3. Go to "Monitoring" in the console and update "myMonitor" to give it a non-zero threshold and a non-zero period.
4. Go to test-a-pipeline again and issue non-valid XML to adapter "TestMonitoring".

Here is the example configuration I applied:

```
<Configuration name="Ibis4Example"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="./FrankConfig-strict.xsd">
        <!--
        <jmsRealms>
              <jmsRealm realmName="jdbc" datasourceName="${jdbc.datasource.default}"/>
        </jmsRealms>
        -->
        <monitoring>
            <destination className="nl.nn.adapterframework.monitoring.GalmMonitorAdapter" name="GALM" />
            <monitor name="myMonitor" destinations="GALM">
                <trigger className="nl.nn.adapterframework.monitoring.Alarm" eventCode="Invalid XML: parser error" severity="WARNING" />
                <trigger className="nl.nn.adapterframework.monitoring.Clearing" eventCode="valid XML" severity="WARNING"/>
            </monitor>
        </monitoring>
        <Adapter name="TestMonitoring">
            <Receiver name="TestMonitoringReceiver">
                <JavaListener name="myListener" serviceName="myListener" />
            </Receiver>
            <Pipeline firstPipe="myPipe">
                <Exit state="success" path="EXIT" />
                <Exit state="error" path="ERROR_EXIT" />
                <XmlWellFormedCheckerPipe name="myPipe">
                    <Forward name="success" path="EXIT" />
                    <Forward name="failure" path="ERROR_EXIT" /> 
                </XmlWellFormedCheckerPipe>
            </Pipeline>
        </Adapter>
</Configuration>
```

**Screenshots**
Here is the exception that occurs:

```
...
Caused by: java.lang.NullPointerException&#xD;
        at nl.nn.adapterframework.monitoring.Trigger.cleanUpEvents(Trigger.java:136)&#xD;
        at nl.nn.adapterframework.monitoring.Trigger.evaluateEvent(Trigger.java:118)&#xD;
        at nl.nn.adapterframework.monitoring.Trigger.evaluateEvent(Trigger.java:100)&#xD;
        at nl.nn.adapterframework.monitoring.Trigger.onApplicationEvent(Trigger.java:92)&#xD;
        ...
```

**Environment**
```
This happened when I was working on PR #2113. I tested by tweaking ibis4example. 
```

**Additional Environment**
 - n/a
 - Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
I think the issue is that variable Trigger.eventDates is only initialized during configure(). It seems that this variable is not initialized to an empty list when a monitor is updated. Then a null pointer exception occurs when the list is accessed.

**Comment by nielsm5** [comment]
See https://github.com/frankframework/frankframework/pull/8017
