### ISSUE TITLE
directorylistener with overwrite="true" still gives FileAlreadyExistsException

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#3810]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
directorylistener gives FileAlreadyExistsException, when files from the procssed folder are processed again despite having overwrite="true" configured

stacktrace:

```txt
2022-10-03 13:09:50,653 ERROR [HandleIndexedDocumentsIn_ProcessFile-listener[857]] null receivers.Receiver - Receiver [HandleIndexedDocumentsIn_ProcessFile] Exception post processing message messageId [NN03102022-095347-895039.ibis.xml] cid [NN03102022-095347-895039.ibis.xml]
nl.nn.adapterframework.core.ListenerException: Cannot change processState to [DONE] for [NN03102022-095347-895039.ibis.xml]: Cannot move file [E:\data\wasap01\fxf-work\hidi\processing\NN03102022-095347-895039.ibis.xml] to [E:\data\wasap01\fxf-work\hidi\processed]: (FileAlreadyExistsException) E:\data\wasap01\fxf-work\hidi\processing\NN03102022-095347-895039.ibis.xml -> E:\data\wasap01\fxf-work\hidi\processed\NN03102022-095347-895039.ibis.xml
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:394) ~[classes/:?]
      at nl.nn.adapterframework.receivers.Receiver.changeProcessState(Receiver.java:847) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:7.7.4-20220907.103832]
      at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1356) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:7.7.4-20220907.103832]
      at nl.nn.adapterframework.receivers.Receiver.processRawMessage(Receiver.java:1078) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:7.7.4-20220907.103832]
      at nl.nn.adapterframework.receivers.Receiver.processRawMessage(Receiver.java:1025) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:7.7.4-20220907.103832]
      at nl.nn.adapterframework.receivers.Receiver.processRawMessage(Receiver.java:1017) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:7.7.4-20220907.103832]
      at nl.nn.adapterframework.receivers.PullingListenerContainer$ListenTask.run(PullingListenerContainer.java:300) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:7.7.4-20220907.103832]
      at java.lang.Thread.run(Thread.java:825) ~[?:2.9 (10-22-2021)]
Caused by: nl.nn.adapterframework.filesystem.FileSystemException: Cannot move file [E:\data\wasap01\fxf-work\hidi\processing\NN03102022-095347-895039.ibis.xml] to [E:\data\wasap01\fxf-work\hidi\processed]: (FileAlreadyExistsException) E:\data\wasap01\fxf-work\hidi\processing\NN03102022-095347-895039.ibis.xml -> E:\data\wasap01\fxf-work\hidi\processed\NN03102022-095347-895039.ibis.xml
      at nl.nn.adapterframework.filesystem.LocalFileSystem.moveFile(LocalFileSystem.java:188) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:?]
      at nl.nn.adapterframework.filesystem.LocalFileSystem.moveFile(LocalFileSystem.java:46) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:?]
      at nl.nn.adapterframework.filesystem.FileSystemUtils.moveFile(FileSystemUtils.java:103) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:?]
      at nl.nn.adapterframework.filesystem.FileSystemListener.changeProcessState(FileSystemListener.java:375) ~[classes/:?]
       ... 7 more
Caused by: java.nio.file.FileAlreadyExistsException: E:\data\wasap01\fxf-work\hidi\processing\NN03102022-095347-895039.ibis.xml -> E:\data\wasap01\fxf-work\hidi\processed\NN03102022-095347-895039.ibis.xml
      at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:93) ~[?:1.8.0]
      at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:109) ~[?:1.8.0]
      at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:399) ~[?:1.8.0]
      at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:299) ~[?:1.8.0]
      at java.nio.file.Files.move(Files.java:1406) ~[?:1.8.0]
      at nl.nn.adapterframework.filesystem.LocalFileSystem.moveFile(LocalFileSystem.java:186) ~[ibis-adapterframework-core-7.7.4-20220907.103832.jar:?]
       ... 10 more
```

**Reporter**
Vinh

**To Reproduce**
1. Error happens on a production windows servers only, testing locally doesnt yield the same error

**Configuration**
```XML
			<listener 
				name="HandleIndexedDocumentsIn_ProcessFile"
				className="nl.nn.adapterframework.receivers.DirectoryListener"
				inputFolder="E:/data/wasap01/fxf-work/hidi/in"
				inProcessFolder="E:/data/wasap01/fxf-work/hidi/processing"
				processedFolder="E:/data/wasap01/fxf-work/hidi/processed"
				wildcard="*.xml"
				overwrite="true"
			/>
```

**Environment**
```
FF! 7.7.4-20220907.103832: Ibis4Scan 57-9578e9e3-master
Running on SRPZZAPP0699 using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pwa6480sr7-20211025_01(SR7))
Heap size: 1339M, total JVM memory: 2048M
Free disk space: 234GB, total disk space: 300GB
Up since: 2022-10-03 08:36:53 (5h)
```

**Additional Environment**
 - Windows 2019 server

**Additional Context**
Not able to reproduce locally

**Comment by gvanbrakel** [comment]
It appears that after a delete, the file is not really deleted. It stays in the directory, with a zero length and a date 1970-01-01.

**Comment by VBPham** [comment]
unzip adapter which places the file in the input folder of the listener

```XML
<adapter name="HandleIndexedDocumentsIn">
	<receiver 
		name="HandleIndexedDocumentsIn">
		<listener className="nl.nn.adapterframework.receivers.JavaListener"
			name="HandleIndexedDocumentsIn" />
	</receiver>

	<pipeline firstPipe="unzip" transactionAttribute="Required">
		<exits>
			<exit path="EXIT" state="success" />
		</exits>

		<pipe 
			name="unzip" 
			className="nl.nn.adapterframework.pipes.UnzipPipe"
			directory="E:/data/wasap01/fxf-work/hidi/in"
			keepOriginalFileName="true"
		>
			<forward name="success" path="EXIT" />
		</pipe>
	</pipeline>
</adapter>
```

input is filelocation string for instance: E:\DATA\wasap01\fxf-work\NNX02419\in\NN04102022-142716232.zip

**Comment by gvanbrakel** [comment]
Might be related to https://stackoverflow.com/questions/4179145/release-java-file-lock-in-windows
