### ISSUE TITLE
Couldn't retrieve remote JWK set: com.ibm.jsse2.util.j: PKIX path building failed

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#4769]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Similair to #3376.

In the use case where one would like to use Azure AD as IDP and accept JWT for authentication on the API listener, the configuration would look as following:

```
<receiver name="Get user">
    <listener uriPattern="user" 
         produces="JSON" 
	 authenticationMethod="JWT" jwksURL="https://login.microsoftonline.com/<tenant-id>/discovery/keys?appid=<client-id>" 
	 requiredClaims="upn" principalClaim="upn" className="nl.nn.adapterframework.http.rest.ApiListener"/>
</receiver>
```

Perfect, this works on a local machine.

Although when deployed on the customers on-premise infrastructure, the following error occurs when calling this API:
`Error 401: Couldn&#39;t retrieve remote JWK set: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target` 

Coressponding stacktrace:
```
2023-04-11 16:12:58,900 WARN [WebContainer : 3] null rest.ApiListenerServlet - unable to validate jwt
com.nimbusds.jose.RemoteKeySourceException: Couldn't retrieve remote JWK set: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
      at com.nimbusds.jose.jwk.source.RemoteJWKSet.updateJWKSetFromURL(RemoteJWKSet.java:167) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jose.jwk.source.RemoteJWKSet.get(RemoteJWKSet.java:260) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jose.proc.JWSVerificationKeySelector.selectJWSKeys(JWSVerificationKeySelector.java:157) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jwt.proc.DefaultJWTProcessor.selectKeys(DefaultJWTProcessor.java:283) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:354) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:303) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:294) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at nl.nn.adapterframework.jwt.JwtValidator.validateJWT(JwtValidator.java:115) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at nl.nn.adapterframework.http.rest.ApiListenerServlet.service(ApiListenerServlet.java:259) ~[classes/:?]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.j2ee.servlet.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:143) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:96) ~[com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
      at nl.nn.adapterframework.http.CacheControlFilter.doFilter(CacheControlFilter.java:55) ~[ibis-adapterframework-core-7.7.3.jar:7.7.3]
      at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:966) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382) ~[com.ibm.ws.webcontainer.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) ~[com.ibm.ws.runtime.jar:?]
Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
      at com.ibm.jsse2.g.a(g.java:43) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bb.a(bb.java:3) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bb.a(bb.java:147) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bb.a(bb.java:117) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.z$c.a(z$c.java:9) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.z$c.a(z$c.java:167) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.z$c.consume(z$c.java:15) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.p.consume(p.java:70) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.aa.a(aa.java:251) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.aa.a(aa.java:260) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bb.a(bb.java:221) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.a0.a(a0.java:7) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bj.b(bj.java:142) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bj.f(bj.java:165) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bj.a(bj.java:338) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.bj.startHandshake(bj.java:519) ~[?:8.0 build_20220616--536]
      at com.ibm.ws.ssl.config.WSSocket.startHandshake(WSSocket.java:414) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:106) ~[?:8.0 build_20220616--536]
      at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:40) ~[?:8.0 build_20220616--536]
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1582) ~[?:1.8.0]
      at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:104) ~[?:1.8.0]
      at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1502) ~[?:1.8.0]
      at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1500) ~[?:1.8.0]
      at java.security.AccessController.doPrivileged(AccessController.java:961) ~[?:1.8.0]
      at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:1009) ~[?:1.8.0]
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1499) ~[?:1.8.0]
      at com.ibm.net.ssl.www2.protocol.https.b.getInputStream(b.java:20) ~[?:8.0 build_20220616--536]
      at com.nimbusds.jose.util.DefaultResourceRetriever.getInputStream(DefaultResourceRetriever.java:305) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jose.util.DefaultResourceRetriever.retrieveResource(DefaultResourceRetriever.java:257) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
      at com.nimbusds.jose.jwk.source.RemoteJWKSet.updateJWKSetFromURL(RemoteJWKSet.java:165) ~[nimbus-jose-jwt-9.15.2.jar:9.15.2]
       ... 40 more
Caused by: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
      at com.ibm.jsse2.util.h.a(h.java:130) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.util.h.b(h.java:180) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.util.g.a(g.java:11) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.br.a(br.java:107) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.br.a(br.java:105) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.br.checkServerTrusted(br.java:22) ~[?:8.0 build_20220616--536]
      at com.ibm.ws.ssl.core.WSX509TrustManager.checkServerTrusted(WSX509TrustManager.java:389) ~[com.ibm.ws.runtime.jar:?]
      at com.ibm.jsse2.bp.checkServerTrusted(bp.java:58) ~[?:8.0 build_20220616--536]
      at com.ibm.jsse2.z$c.a(z$c.java:80) ~[?:8.0 build_20220616--536]
       ... 65 more
Caused by: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
      at com.ibm.security.cert.SunCertPathBuilder.build(SunCertPathBuilder.java:139) ~[?:8.0 build_20220531-172]
      at com.ibm.security.cert.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:124) ~[?:8.0 build_20220531-172]
      at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:292) ~[?:?]
      at com.ibm.jsse2.util.h.a(h.java:33) ~[?:8.0 build_20220616--536]
       ... 73 more
```

I decided to add the custom certificate pipe from #3376 to the application and confirmed that the certificate is present:
![image](https://user-images.githubusercontent.com/37303445/231192893-eb9005f6-0af2-4d08-b6bf-5385e66d9f27.png)

I decided to test with a regular http sender what would happen:
![image](https://user-images.githubusercontent.com/37303445/231193362-263ca79f-96c1-408a-b55e-1c34ae92ecad.png)

I decided to test with a custom http sender where I'd set the keystore location explicitly:
![image](https://user-images.githubusercontent.com/37303445/231193666-0087163e-0c60-4e33-82b7-ef0a9ccfda4f.png)

**Reporter**
Laurens

**Comment by nielsm5** [comment]
It's very difficult to analyze this, as we mentioned in #3376, the SSL Context is provided by WebSphere, and that's where the problem originates from. Using your own key/truststore will circumvent the WebSphere keystore completely, and will give you more control over the SSL Context.

**Comment by Laurens-makel** [comment]
The custom certificate pipe in #3376 shows that the **default** keystore is used to list all certificates present in the keystore:
![image](https://user-images.githubusercontent.com/37303445/232558646-d8013aa8-ffc9-42d6-a001-218c29db6b1b.png)

Related documentation:
https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html
![image](https://user-images.githubusercontent.com/37303445/232558680-28c31e08-3ae4-4fbc-833b-182a8a26f2d6.png)


The custom sender does indeed work with a custom keystore location, although the attribute is configured to use the default trust/keystore from WAS... I did not add a custom trust/keystore myself...

![image](https://user-images.githubusercontent.com/37303445/232559222-0f67801b-9b61-4d83-81fe-878e8f696f88.png)

**Comment by nielsm5** [comment]
I'm sorry, I don't fully understand the question... Please don't try to solve the problem in an issue report, describe it. If you already have a solution, a PR would be a better fit. 
Is your question if we can implement a way to provide a custom KeyStore for the ApiListener?

**Comment by Laurens-makel** [comment]
The previous comment should not be considered as an attempt to fix a problem.

Since your first comment implies that I am using a custom store, I am providing additional information on the problem case, PKIX exception, which also proofs that I am not using a custom store.

Things I've verified:
1. Verified presence of the correct certificate
2. Verified that with a custom SSL context (configured to use the **default** store) the request could be made successfully

My questions is, what could be wrong in the default SSL context that would cause such error? Or reverse the question, why does it work in the custom SSL context implementation (considering I am using the default store!)?

**Comment by nielsm5** [comment]
It's not just the certificate that has to be present but the entire 'Chain of Trust'.
It looks like Nimbusds uses `sun.net.www.protocol.http.HttpURLConnection.getInputStream0(...)` to connect to an endpoint, I believe this is the default and it's currently not possible to configure the SSLSocketFactory. What happens deep inside the IBM JDK is a mystery. Your tests are not applicable to the stacktrace provided, as that's purely related to Nimbusds retrieving the JWK set.
