### ISSUE TITLE
"Silent Rollback" during commit breaks error handling

### ISSUE THREAD

**Issue by tnleeuw** [frankframework/frankframework#4822]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**

When a commit is done on a transaction that is marked for rollback-only, normally this will throw an `UnexpectedRollbackException`.

This exception is now suppressed in the `SpringTxManagerProxy` by an explicit check if the transaction is marked "rollback only" and doing the rollback ourselves, without exceptions.

This means that error handling paths are not executed and error handling is in a number of instances broken, because code continues under the assumption that successful commit means no error.

This was introduced while attempting to fix Issue #1417 in PR #1425 so we need to better understand the root cause of that issue too and make sure not to re-introduce the problem.

This issue likely has as root-cause incorrect transaction handling in the `PullingListeningContainer`, when looking at the stack trace attached to that issue.

**Reporter**
Tim van der Leeuw

**Comment by nielsm5** [comment]
```
jta.SpringTxManagerProxy - <TX> Executing silent rollback without exception from tx.commit! TransactionStatus: [org.springframework.transaction.support.DefaultTransactionStatus@6bef1fca], Stacktrace:
java.lang.Exception: <TX> Warning - Silent rollback from commit
      at nl.nn.adapterframework.jta.SpringTxManagerProxy.commit(SpringTxManagerProxy.java:70) [ibis-adapterframework-core-7.9.2-20240327.230121.jar:7.9.2-20240327.230121]
      at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) [spring-jms-5.3.33.jar:5.3.33]
      at nl.nn.adapterframework.jms.IbisMessageListenerContainer.receiveAndExecute(IbisMessageListenerContainer.java:90) [ibis-adapterframework-core-7.9.2-20240327.230121.jar:7.9.2-20240327.230121]
      at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) [spring-jms-5.3.33.jar:5.3.33]
      at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1127) [spring-jms-5.3.33.jar:5.3.33]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) [?:1.8.0]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:1.8.0]
      at java.lang.Thread.run(Thread.java:825) [?:2.9 (09-08-2023)]
```

**Comment by nielsm5** [comment]
Linking #4655
