### ISSUE TITLE
Exception is not correctly handled 

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#5203]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I have a transactional Pipeline. In the pipeline I use PutInSessionPipe and the pipe has an exception forward which follows another PutInSessionPipe. In the first pipe I am getting a parameter value by using an xpathExpression. Calculating the parameter value throws an exception and the pipeline follows the exception forward. 

![image](https://github.com/ibissource/iaf/assets/10929856/8f6ec07f-06e1-4db9-b0b6-895d14e29d78)

When an exception is thrown from the PutInSessionPipe the transaction is set rollback only. Further down in the pipeline I use a JmsSender to send a message. Since the transaction is already marked as rollback only JmsSender throws an error when enlisting the transaction.

`Caused by: javax.jms.JMSException: error enlisting a MessageProducerWrapper of a DualSessionWrapper in state ACCESSIBLE of a JmsPooledConnection of pool jms/qcf_tibco_esb_ff in state ACCESSIBLE with underlying connection XAQueueConnection[ClientId=null, Connected=ssl:MASKED, URL=ssl:MASKED,ssl://MASKED]
      at bitronix.tm.resource.jms.MessageProducerWrapper.enlistResource(MessageProducerWrapper.java:61)
      at bitronix.tm.resource.jms.MessageProducerWrapper.send(MessageProducerWrapper.java:75)
      at nl.nn.adapterframework.jms.JMSFacade.send(JMSFacade.java:651)
      at nl.nn.adapterframework.jms.JMSFacade.send(JMSFacade.java:628)
      at nl.nn.adapterframework.jms.JmsSender.sendMessage(JmsSender.java:216)
      ... 258 more
Caused by: bitronix.tm.internal.BitronixRollbackException: transaction has been marked as rollback only
      at bitronix.tm.BitronixTransaction.enlistResource(BitronixTransaction.java:113)
      at bitronix.tm.resource.common.TransactionContextHelper.enlistInCurrentTransaction(TransactionContextHelper.java:68)
      at bitronix.tm.resource.jms.MessageProducerWrapper.enlistResource(MessageProducerWrapper.java:57)
      ... 262 more`

The workaround seems to be setting the `transactionAttribute="NotSupported"` in **PutInSessionPipes**. However, it is not easy to identify such issue. It can easily be overlooked. 

In this case the exception is tolerated in the pipeline. The exception might be thrown from the pipe and is already handled in the pipeline. The correct behaviour would be not to mark the transaction rollback only. 

**Reporter**
Ali

FF: 7.9-20230802.192100

**Comment by nielsm5** [comment]
Since the #1149 the IbisTransaction actually does a rollback instead of a commit.

**Comment by Laurens-makel** [comment]
Ran into a similair situation on the 7.8 release today, exception was thrown and succesfully handled, adapter ended with state success but the tx still rollbacked..

**Comment by nielsm5** [comment]
See also #4822
