### ISSUE TITLE
Unclear "content already set as string" error message when Xml2JsonValidator input does not validate against schema when translating Xml to Json

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#5497]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Using a schema to assist with correctly translating Xml to Json. Schema contains a single element with a sequence. Errors does suggests an alignment issue, but it is also referring to the root element already being set to a string. From a user perspective this error is complete gibberish. 

I would at the very least expect an error that mentions that the **validation** failed, as the word alignment doesn't make sense if you don't know the technical implementation of this pipe. Preferably with a more detailed summary of what is wrong similar to what you would get when simply validating Xml instead of also translating Xml to Json.

**Reporter**
M. Lenterman

**To Reproduce**
[Pipeline zaak_create_db.zip](https://github.com/ibissource/iaf/files/12802449/Pipeline.zaak_create_db.zip)

**Screenshots**

**Configuration**
```xml
<Json2XmlValidatorPipe
	name="XmlToJson"
	schema="Zgw/Zaken/Model/PostZgwZaak.xsd"
	outputFormat="JSON"
	deepSearch="true"
	throwException="true"
        >
	<Forward name="success" path="Created"/>
        <Forward name="error" path="InternalServerError"/>
</Json2XmlValidatorPipe>
```

**Input**
[Xml2JsonValidator - XSDs.zip](https://github.com/ibissource/iaf/files/12802403/Xml2JsonValidator.-.XSDs.zip)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ZgwZaak>
	<url>http://host.docker.internal:9000/zaken/api/v1/zaken/ac1a0008-25ff7b7a_18afa2810c2_-7fff</url>
	<identificatie>5</identificatie>
	<bronorganisatie>002220647</bronorganisatie>
	<omschrijving>Zaak naar aanleiding van ingezonden formulier</omschrijving>
	<toelichting>Aangemaakt door Open Formulieren</toelichting>
	<zaaktype>http://host.docker.internal:9000/catalogi/api/v1/zaaktypen/363039fd-4700-4f9b-b00f-7c9e8bf2a142</zaaktype>
	<registratiedatum>2023-09-22</registratiedatum>
	<verantwoordelijkeOrganisatie>002220647</verantwoordelijkeOrganisatie>
	<startdatum>2023-09-22</startdatum>
	<vertrouwelijkheidaanduiding>zaakvertrouwelijk</vertrouwelijkheidaanduiding>
	<betalingsindicatie>nog_niet</betalingsindicatie>
	<archiefnominatie>blijvend_bewaren</archiefnominatie>
</ZgwZaak>
```

**Environment**
```
FF! 7.9-20230905.223421: Openforms2bpel 1.0.0
Running on 1621400cd791 using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20.1+1)
Heap size: 780M, total JVM memory: 1824M
Free disk space: 203GB, total disk space: 251GB
Up since: 2023-10-04 12:17:14 (37m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
```
nl.nn.adapterframework.core.PipeRunException: Pipe [XmlToJson] Alignment of XML to JSON failed: (IllegalStateException) content already set as String for element [ZgwZaak]
	at nl.nn.adapterframework.pipes.Json2XmlValidator.doPipe(Json2XmlValidator.java:197)
	at nl.nn.adapterframework.pipes.ValidatorBase.doPipe(ValidatorBase.java:75)
	at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:33)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:38)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:62)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:61)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:59)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:67)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:187)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$a9371776.processPipe(<generated>)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:113)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:202)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$a8a8fc9a.processPipe(<generated>)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.ExceptionHandlingPipeProcessor.processPipe(ExceptionHandlingPipeProcessor.java:37)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:77)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:237)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$8b5c92ba.processPipeLine(<generated>)
	at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:60)
	at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:49)
	at nl.nn.adapterframework.processors.CheckSemaphorePipeLineProcessor.processPipeLine(CheckSemaphorePipeLineProcessor.java:58)
	at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:41)
	at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:44)
	at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:501)
	at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:664)
	at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1232)
	at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1040)
	at nl.nn.adapterframework.http.PushingListenerAdapter.processRequest(PushingListenerAdapter.java:103)
	at nl.nn.adapterframework.http.rest.ApiListener.processRequest(ApiListener.java:151)
	at nl.nn.adapterframework.http.rest.ApiListenerServlet.handleRequest(ApiListenerServlet.java:528)
	at nl.nn.adapterframework.http.rest.ApiListenerServlet.service(ApiListenerServlet.java:202)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:164)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: content already set as String for element [ZgwZaak]
	at nl.nn.adapterframework.align.content.JsonElementContainer.addContent(JsonElementContainer.java:168)
	at nl.nn.adapterframework.align.content.JsonDocumentContainer.addContent(JsonDocumentContainer.java:60)
	at nl.nn.adapterframework.align.content.JsonDocumentContainer.addContent(JsonDocumentContainer.java:34)
	at nl.nn.adapterframework.align.content.TreeContentContainer.endElement(TreeContentContainer.java:49)
	at nl.nn.adapterframework.align.XmlTo.endElement(XmlTo.java:154)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(Unknown Source)
	at nl.nn.adapterframework.align.XmlAligner.endElement(XmlAligner.java:181)
	at org.apache.xerces.jaxp.validation.ValidatorHandlerImpl.endElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.endElement(Unknown Source)
	at org.apache.xerces.jaxp.validation.ValidatorHandlerImpl.endElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at nl.nn.adapterframework.util.XmlUtils.parseXml(XmlUtils.java:488)
	at nl.nn.adapterframework.validation.AbstractXmlValidator.validate(AbstractXmlValidator.java:223)
	at nl.nn.adapterframework.validation.AbstractXmlValidator.validate(AbstractXmlValidator.java:218)
	at nl.nn.adapterframework.pipes.Json2XmlValidator.alignXml2Json(Json2XmlValidator.java:249)
	at nl.nn.adapterframework.pipes.Json2XmlValidator.doPipe(Json2XmlValidator.java:195)
	... 160 more

```

**Comment by nielsm5** [comment]
It seems that the Validator attempts to convert the input xml, which contains an element that's not in the XSD (url).
It looks likes it attempts to map the element to the root element, and is then not able to add more elements (as the root is not seen as an object but a string).

**Comment by evandongen** [comment]
Just like Niels said. If the json already contains a String, It can't have another element at the same level. Fixed the error message to be more clear and point the user to where this might've gone wrong.

**Comment by tnleeuw** [comment]
Do you know what the string is, that it contains at that moment? Is it just whitespace or is it perhaps, actually, the value of that URL attribute that is not valid according to XSD?
I'm just curious what is the actual behaviour of the code with this non-conforming input.

**Comment by evandongen** [comment]
It's the url value which is added as a string, instead of an element. The next element to be added will fail because of this. See the unit test I created: `org.frankframework.validation.Json2XmlValidatorTest#testContentAlreadySetAsStringHandled`
