### ISSUE TITLE
download and resend not working in combination with file time sensitive in directory listener

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#5748]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When trying to download (or resend) an error message from the directory listener GUI the download fails because it finds a  %25 (instead of a space) this gives an error.

14-Nov-2023 10:48:42.141 SEVERE [http-nio-80-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [IAF-API] in context with path [] threw exception
      org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "%25"
            at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:535)
            at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:505)
            at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:210)
            at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)
            at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
            at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
            at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:596)
            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
            at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
            at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
            at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
            at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
            at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
            at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
            at java.lang.Thread.run(Thread.java:748)

**Reporter**
Eddy /Jeroen

**Screenshots**

**Configuration**
```
<Adapter name="MFHIn_00109" active="${active.mfh}" description="Create trigger in the IBISFILETRIGGER table for legacy flow 00109">
        <Receiver pollInterval="${mfh.MFHIn_00109.pollInterval}">
            <DirectoryListener
                minStableTime ="${mfh.MFHIn_00109.minstabletime}"
                fileTimeSensitive="true"
                name="MFHIn"
                messageType="info"
                root="${mfh.MFHIn_00109.rootdir}"
                inputFolder="in"
                inProcessFolder="inProcess"
                errorFolder="error"
                createFolders="true"
                wildcard="${mfh.MFHIn_00109.wildcard}"/>
        </Receiver>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
was working on 7.7.3

FF! 7.8.3: Ibis4SapCD
Running on LPCENL005288323 using Apache Tomcat/9.0.74
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 357M, total JVM memory: 604M
Free disk space: 101GB, total disk space: 238GB
Up since: 2023-11-14 12:44:45 (8m)
has context menu
 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by tnleeuw** [comment]
Having managed to reproduce this, I see that the download-link contains `%2520` where the original filename had a ` ` (space). (There are still other spaces in the download link though, oddly enough...)

http://localhost:8080/iaf-test/iaf/api/configurations/FileHandling/adapters/MFHIn/receivers/DirectoryListener%20%5BMFHIn%5D/stores/Error/messages/mfh-input.xml-2023-03-08%252019_23_41.283/download

However the JSON data does not contain neither the %25 nor %20, it still has the original spaces in the filename.

So I guess the download-error is an issue with the front end doing double url-encoding on parts of the URL being constructed.

**Comment by nielsm5** [comment]
https://github.com/frankframework/frankframework/blob/bc99f5eb894ba4e2ff9014a79f6e82cd52869624/console/backend/src/main/java/nl/nn/adapterframework/management/web/CompatiblityTransactionalStorage.java#L73

**Comment by tnleeuw** [comment]
So we screw up one use-case to "fix" another.

I suggest that either we put the mangling of the message-ids in the Exchange listener, or we do a safe manging and unmangling all in the back-end and not one part in the front-end and another part in the back-end.
