### ISSUE TITLE
InvalidMimeTypeException: Invalid token character

### ISSUE THREAD

**Issue by rvdstel** [frankframework/frankframework#5920]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In version FF! 7.8.3-hotfix1 we get a lot of warnings in the logs with InvalidMimeTypeException. We do not think there is anything wrong with the input.

unable to parse mimetype from string [multipart/related;boundary=4444ab3725b048db84aa8d60c8db9a76;type=application/xop+xml;start=<rootpart@root.part>;start-info=text/xml] org.springframework.util.InvalidMimeTypeException: 
Invalid mime type "multipart/related;boundary=4444ab3725b048db84aa8d60c8db9a76;type=application/xop+xml;start=<rootpart@root.part>;start-info=text/xml": 	'/' in token "application/xop+xml"

unable to parse mimetype from string [application/pdf;name=581031 23-019523BP Kwitantie bon_new.pdf]
org.springframework.util.InvalidMimeTypeException: 
Invalid mime type "application/pdf;name=581031 23-019523BP Kwitantie bon_new.pdf": Invalid token character ' ' in token "581031 23-019523BP Kwitantie bon_new.pdf"

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
2023-11-29 00:12:12,979 WARN [WebContainer : 6] {} stream.MessageContext - unable to parse mimetype from string [multipart/related;boundary=3f4718e824b94b9d894ad7f9ace7692f;type=application/xop+xml;start=<rootpart@root.part>;start-info=text/xml]
org.springframework.util.InvalidMimeTypeException: Invalid mime type "multipart/related;boundary=3f4718e824b94b9d894ad7f9ace7692f;type=application/xop+xml;start=<rootpart@root.part>;start-info=text/xml": Invalid token character '/' in token "application/xop+xml"
at org.springframework.util.MimeTypeUtils.parseMimeTypeInternal(MimeTypeUtils.java:275) ~[spring-core-5.3.30.jar:5.3.30]
at org.springframework.util.MimeTypeUtils.parseMimeType(MimeTypeUtils.java:207) ~[spring-core-5.3.30.jar:5.3.30]
at org.springframework.util.MimeType.valueOf(MimeType.java:615) ~[spring-core-5.3.30.jar:5.3.30]
at nl.nn.adapterframework.stream.MessageContext.withMimeType(MessageContext.java:76) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
at nl.nn.adapterframework.http.cxf.SOAPProviderBase.parseSOAPMessage(SOAPProviderBase.java:319) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
at nl.nn.adapterframework.http.cxf.SOAPProviderBase.invoke(SOAPProviderBase.java:149) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
... suppressed 3 lines

2023-11-29 14:56:05,898 WARN [WebContainer : 5] {} stream.MessageContext - unable to parse mimetype from string [application/pdf;name=581031 23-019523BP Kwitantie bon_new.pdf]
org.springframework.util.InvalidMimeTypeException: Invalid mime type "application/pdf;name=581031 23-019523BP Kwitantie bon_new.pdf": Invalid token character ' ' in token "581031 23-019523BP Kwitantie bon_new.pdf"
at org.springframework.util.MimeTypeUtils.parseMimeTypeInternal(MimeTypeUtils.java:275) ~[spring-core-5.3.30.jar:5.3.30]
at org.springframework.util.ConcurrentLruCache.get(ConcurrentLruCache.java:107) ~[spring-core-5.3.30.jar:5.3.30]
at org.springframework.util.MimeTypeUtils.parseMimeType(MimeTypeUtils.java:209) ~[spring-core-5.3.30.jar:5.3.30]
at org.springframework.util.MimeType.valueOf(MimeType.java:615) ~[spring-core-5.3.30.jar:5.3.30]
at nl.nn.adapterframework.stream.MessageContext.withMimeType(MessageContext.java:76) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
at nl.nn.adapterframework.util.MessageUtils.getContext(MessageUtils.java:91) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
at nl.nn.adapterframework.util.MessageUtils.parse(MessageUtils.java:116) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
at nl.nn.adapterframework.http.cxf.SOAPProviderBase.invoke(SOAPProviderBase.java:134) [ibis-adapterframework-core-7.8.3-hotfix1.jar:7.8.3-hotfix1]
... suppressed 3 lines

**Comment by nielsm5** [comment]
De filename is wel echt fout! Die melding zal zeker blijven, voor het lezen van een multipart mimetype zullen we iets inbouwen 😄
