### ISSUE TITLE
NG0900 on opening security items in the console

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#6055]
**Describe the issue**
NG0900 when opening the security-items page in the console, page is empty.
API endpoint for security items probably gave something unexpected back, the API response is needed in order to find the root of the issue

**Reporter**
@diedekerkhof

**Stack trace**
```
main.10fbedf53c0019c7.js:1 ERROR Error: NG0900
    at hae.diff (main.10fbedf53c0019c7.js:1:127079)
    at t.ngDoCheck (main.10fbedf53c0019c7.js:1:157131)
    at yee (main.10fbedf53c0019c7.js:1:25362)
    at kV (main.10fbedf53c0019c7.js:1:25129)
    at u4 (main.10fbedf53c0019c7.js:1:24806)
    at O4 (main.10fbedf53c0019c7.js:1:57139)
    at Dre (main.10fbedf53c0019c7.js:1:57487)
    at O4 (main.10fbedf53c0019c7.js:1:57513)
    at Are (main.10fbedf53c0019c7.js:1:64419)
    at are (main.10fbedf53c0019c7.js:1:57926)
```

**Environment**
Missing

**Additional Environment**
Missing

**Additional Context**
Missing

**Comment by Matthbo** [comment]
Reminder to self, see API response in email
