### ISSUE TITLE
mvn jetty:run doesn't work

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6063]
**Describe the issue**
When following https://github.com/frankframework/frankframework/blob/master/CONTRIBUTING.md#running-the-frankframework the end result is:

```
HTTP ERROR 503 Service Unavailable
URI:	/iaf/ladybug
STATUS:	503
MESSAGE:	Service Unavailable
SERVLET:	-
Powered by Jetty:// 10.0.19
```

In the console a lot of log.dir related errors are shown. So I tried with:

mvn -Dlog.dir=C:\Temp\jetty jetty:run

Now it only shows the  following stacktrace (twice):

```
[INFO] Enabling Spring WebSecurity
2024-01-02 15:11:08,921 - IBIS ApplicationInitializer failed to initialize
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalStateException: unable to configure Spring Security
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:481) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929) ~[spring-context-5.3.31.jar:5.3.31]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) ~[spring-context-5.3.31.jar:5.3.31]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:399) ~[spring-web-5.3.31.jar:5.3.31]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:278) ~[spring-web-5.3.31.jar:5.3.31]
        at org.frankframework.lifecycle.FrankEnvironmentInitializer.onStartup(FrankEnvironmentInitializer.java:66) [frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174) [spring-web-5.3.31.jar:5.3.31]
        at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148) [jetty-servlet-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1658) [jetty-servlet-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369) [jetty-servlet-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) [jetty-webapp-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901) [jetty-server-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) [jetty-servlet-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) [jetty-webapp-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.maven.plugin.MavenWebAppContext.doStart(MavenWebAppContext.java:294) [jetty-maven-plugin-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.server.Server.start(Server.java:470) [jetty-server-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.server.Server.doStart(Server.java:415) [jetty-server-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.maven.plugin.JettyEmbedder.doStart(JettyEmbedder.java:224) [jetty-maven-plugin-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.maven.plugin.JettyRunMojo.startJettyEmbedded(JettyRunMojo.java:97) [jetty-maven-plugin-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.maven.plugin.AbstractWebAppMojo.startJetty(AbstractWebAppMojo.java:441) [jetty-maven-plugin-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.maven.plugin.AbstractWebAppMojo.execute(AbstractWebAppMojo.java:419) [jetty-maven-plugin-10.0.19.jar:10.0.19]
        at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:85) [jetty-maven-plugin-10.0.19.jar:10.0.19]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101) [maven-core-3.9.5.jar:3.9.5]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906) [maven-embedder-3.9.5.jar:3.9.5]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283) [maven-embedder-3.9.5.jar:3.9.5]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:206) [maven-embedder-3.9.5.jar:3.9.5]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283) [plexus-classworlds-2.7.0.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226) [plexus-classworlds-2.7.0.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407) [plexus-classworlds-2.7.0.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348) [plexus-classworlds-2.7.0.jar:?]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalStateException: unable to configure Spring Security
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.31.jar:5.3.31]
        ... 78 more
Caused by: java.lang.IllegalStateException: unable to configure Spring Security
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.configureHttpSecurity(ServletAuthenticatorBase.java:179) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.createSecurityFilterChain(ServletAuthenticatorBase.java:151) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.build(ServletAuthenticatorBase.java:146) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.ServletManager.startAuthenticators(ServletManager.java:134) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer.init(HttpSecurityConfigurer.java:73) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer.init(HttpSecurityConfigurer.java:43) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer$$EnhancerBySpringCGLIB$$36c262ff.init(<generated>) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:344) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:306) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:125) ~[spring-security-config-5.8.9.jar:5.8.9]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.31.jar:5.3.31]
        ... 78 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.web.authentication.preauth.j2ee.WebXmlMappableAttributesRetriever': Invocation of init method failed; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/web.xml]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.frankframework.util.SpringUtils.createBean(SpringUtils.java:26) ~[frankframework-commons-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.getWebXmlSecurityRoles(JeeAuthenticator.java:93) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.getAuthenticationDetailsSource(JeeAuthenticator.java:86) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.getProcessingFilter(JeeAuthenticator.java:78) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.configure(JeeAuthenticator.java:48) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.configureHttpSecurity(ServletAuthenticatorBase.java:177) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.createSecurityFilterChain(ServletAuthenticatorBase.java:151) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.build(ServletAuthenticatorBase.java:146) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.ServletManager.startAuthenticators(ServletManager.java:134) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer.init(HttpSecurityConfigurer.java:73) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer.init(HttpSecurityConfigurer.java:43) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer$$EnhancerBySpringCGLIB$$36c262ff.init(<generated>) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:344) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:306) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:125) ~[spring-security-config-5.8.9.jar:5.8.9]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.31.jar:5.3.31]
        ... 78 more
Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/web.xml]
        at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:165) ~[spring-web-5.3.31.jar:5.3.31]
        at org.springframework.security.web.authentication.preauth.j2ee.WebXmlMappableAttributesRetriever.afterPropertiesSet(WebXmlMappableAttributesRetriever.java:85) ~[spring-security-web-5.8.9.jar:5.8.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.frankframework.util.SpringUtils.createBean(SpringUtils.java:26) ~[frankframework-commons-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.getWebXmlSecurityRoles(JeeAuthenticator.java:93) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.getAuthenticationDetailsSource(JeeAuthenticator.java:86) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.getProcessingFilter(JeeAuthenticator.java:78) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.JeeAuthenticator.configure(JeeAuthenticator.java:48) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.configureHttpSecurity(ServletAuthenticatorBase.java:177) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.createSecurityFilterChain(ServletAuthenticatorBase.java:151) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.ServletAuthenticatorBase.build(ServletAuthenticatorBase.java:146) ~[frankframework-security-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.ServletManager.startAuthenticators(ServletManager.java:134) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer.init(HttpSecurityConfigurer.java:73) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer.init(HttpSecurityConfigurer.java:43) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.frankframework.lifecycle.servlets.HttpSecurityConfigurer$$EnhancerBySpringCGLIB$$36c262ff.init(<generated>) ~[frankframework-core-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:344) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:306) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38) ~[spring-security-config-5.8.9.jar:5.8.9]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:125) ~[spring-security-config-5.8.9.jar:5.8.9]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.31.jar:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.31.jar:5.3.31]
        ... 78 more
```

**Reporter**
Jaco de Groot

**To Reproduce**
1. Follow https://github.com/frankframework/frankframework/blob/master/CONTRIBUTING.md#running-the-frankframework
2. See error

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
Made a new clone of https://github.com/frankframework/frankframework.git just before reporting this issue

**Additional Environment**
\-

**Additional Context**
\-

**Comment by jacodg** [comment]
P.s. in the instrctions "cd iaf" should be "cd frankframework"

**Comment by mhdirkse** [comment]
It does work on the 7.9-release branch (commit https://github.com/frankframework/frankframework/commit/fbf05022202ec0b045302ef1706629f00ebc5dd6), if the Maven build is done with -DskipTests.

**Comment by mhdirkse** [comment]
Als je web.xml van het webapp project kopiëert, dan boot het F!F. In de console krijg je dan permission denied. Je moet dan ook nog log.dir opgeven met de -D optie, terwijl log.dir ingevuld is in de pom.xml van het example project. Ik vermoed dat de `<configuration>` sectie die bij de Jetty Maven plugin staat geen effect heeft. Ik heb hierover met Tim overlegd, die suggereerde dat een andere versie van de Jetty Maven plugin mogelijk beter werkt.

**Comment by mhdirkse** [comment]
Ik heb geprobeerd een log statement in de source code van het F!F te zetten. Je ziet dan dat system property log.dir inderdaad geen waarde heeft als je hem niet met -D meegeeft.

**Comment by nielsm5** [comment]
We've removed the Jetty example.
