### ISSUE TITLE
Many unit tests related to file systems fail on Martijn-s laptop

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#6096]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
On Martijn-s laptop, `mvn clean install` produces many failing unit tests, one of them being Samba2FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot. This issue does not appear on Tim's development, not in GitHub actions and not on Jenkins. The issue appears both on the master branch (commit 7e3fe213d47cb39de27709838ad4a7005474f6f9) and the 7.9-release branch (commit fbf05022202ec0b045302ef1706629f00ebc5dd6).

Martijn could reproduce the issue in Eclipse
![image](https://github.com/frankframework/frankframework/assets/6784732/eb745c45-c481-4a33-9587-db0d0393e502)

He added some additional logging to the test as shown below:

![image](https://github.com/frankframework/frankframework/assets/6784732/06bcac6a-a66e-45a8-9edf-b59d9958ac21)

The log output is:

```
10:58:11,784 INFO  Samba2FileSystemTest.setUp():42[] Test in Samba2FileSystemTest [org.frankframework.filesystem.smb.Samba2FileSystemTest.null]
*** JFileServer Enterprise edition licenced to Frank!Framework (Niels Meijer/niels@frankframework.org/3)
***  For version 1.*
10:58:11,908 INFO  BasicFileSystemTest.setUp():42[] Test in BasicFileSystemTest [org.frankframework.filesystem.smb.Samba2FileSystemTest.null]
10:58:11,908 INFO  BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot():482[] Test basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot
10:58:11,908 INFO  BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot():483[] Clean root folder
10:58:11,908 INFO  BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot():485[] Create folder 'folder'
10:58:11,909 INFO  BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot():487[] Create folder 'Otherfolder'
10:58:11,909 INFO  BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot():489[] Create file
10:58:11,910 INFO  BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot():491[] List file
```

The line `10:58:11,908 INFO  BasicFileSystemTest.setUp():42[] Test in BasicFileSystemTest [org.frankframework.filesystem.smb.Samba2FileSystemTest.null]` comes from added code in BasicFileSystemTest.java:

![image](https://github.com/frankframework/frankframework/assets/6784732/c6a26dfc-a601-46ed-ac58-35ccf0596f3c)

This rule is applied in the setUp() methods to display the name of the test, although the name is rendered incorrectly as null.

When Martijn discussed with Tim van der Leeuw, it struck Jim that the createFile() calls in the test succeeded while the basicFileSystemTestListFile() call failed.

The test succeeded when it was run in Eclipse without running other tests. The information given here was produced by running all tests of package org.frankframework.filesystem.smb.

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
This issue is related to #6063

**Comment by mhdirkse** [comment]
Maven and Java versions:

```
C:\Users\martijn\git\frankframework>mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\martijn\Programmas\apache-maven-3.6.3-bin\apache-maven-3.6.3\bin\..
Java version: 11.0.15, vendor: Eclipse Adoptium, runtime: C:\Users\martijn\Programmas\OpenJDK11U-jdk_x64_windows_hotspot_11.0.15_10\jdk-11.0.15+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

C:\Users\martijn\git\frankframework>
```

Eclipse:

```
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2021-09 (4.21.0)
Build id: 20210910-1417

(c) Copyright Eclipse contributors and others 2000, 2021.  All rights reserved. Eclipse and the Eclipse logo are trademarks of the Eclipse Foundation, Inc., https://www.eclipse.org/. The Eclipse logo cannot be altered without Eclipses permission. Eclipse logos are provided for use under the Eclipse logo and trademark guidelines, https://www.eclipse.org/logotm/. Oracle and Java are trademarks or registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

This product includes software developed by other open source projects including the Apache Software Foundation, https://www.apache.org/.

Lombok v1.18.22 "Envious Ferret" is installed. https://projectlombok.org/
```

**Comment by nielsm5** [comment]
What happens when you run the tests without the proprietary profile?

**Comment by mhdirkse** [comment]
`mvn -P!proprietary clean install` does not work, but the error is different:

```
[INFO]
[INFO] ---------------< org.frankframework:frankframework-aws >----------------
[INFO] Building Frank!Framework support for AWS 8.1.0-SNAPSHOT          [16/25]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ frankframework-aws ---
[INFO] Deleting C:\Users\martijn\git\frankframework\aws\target
[INFO]
[INFO] --- flatten-maven-plugin:1.5.0:clean (clean) @ frankframework-aws ---
[INFO] Deleting C:\Users\martijn\git\frankframework\aws\.flattened-pom.xml
[INFO]
[INFO] --- maven-enforcer-plugin:3.4.1:enforce (enforce-lib-ban) @ frankframework-aws ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Rule 1: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Rule 2: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Rule 3: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Rule 4: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO]
[INFO] --- maven-enforcer-plugin:3.4.1:enforce (enforce-classpath-lib-ban) @ frankframework-aws ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO]
[INFO] --- directory-maven-plugin:1.0:directory-of (find-project-root-directory) @ frankframework-aws ---
[INFO] Directory of org.frankframework:frankframework-parent set to: C:\Users\martijn\git\frankframework
[INFO]
[INFO] --- flatten-maven-plugin:1.5.0:flatten (flatten) @ frankframework-aws ---
[INFO] Generating flattened POM of project org.frankframework:frankframework-aws:jar:8.1.0-SNAPSHOT...
[INFO]
[INFO] --- glassfish-copyright-maven-plugin:2.4:copyright (Check-CopyRight-Notice) @ frankframework-aws ---
[INFO]
[INFO] --- glassfish-copyright-maven-plugin:2.4:check (Check-CopyRight-Notice) @ frankframework-aws ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ frankframework-aws ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\martijn\git\frankframework\aws\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ frankframework-aws ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 7 source files with javac [debug release 11] to target\classes
[INFO]
[INFO] --- maven-checkstyle-plugin:3.3.1:check (verify-code-style) @ frankframework-aws ---
[INFO] You have 0 Checkstyle violations.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ frankframework-aws ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.11.0:testCompile (default-testCompile) @ frankframework-aws ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 5 source files with javac [debug release 11] to target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ frankframework-aws ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.frankframework.filesystem.AmazonS3FileSystemTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in org.frankframework.filesystem.AmazonS3FileSystemTest
[ERROR] org.frankframework.filesystem.AmazonS3FileSystemTest  Time elapsed: 0.01 s  <<< ERROR!
java.lang.NoClassDefFoundError: Lorg/junit/rules/TestName;
Caused by: java.lang.ClassNotFoundException: org.junit.rules.TestName

[INFO] Running org.frankframework.jms.AmazonSqsFactoryTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.79 s - in org.frankframework.jms.AmazonSqsFactoryTest
[INFO] Running org.frankframework.senders.AmazonS3SenderTest
[INFO] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.531 s - in org.frankframework.senders.AmazonS3SenderTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   AmazonS3FileSystemTest » NoClassDefFound Lorg/junit/rules/TestName;
[INFO]
[ERROR] Tests run: 36, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Frank!Framework parent 8.1.0-SNAPSHOT:
[INFO]
[INFO] Frank!Framework parent ............................. SUCCESS [  8.170 s]
[INFO] Frank!Framework Commons ............................ SUCCESS [ 16.784 s]
[INFO] Frank!Framework Security ........................... SUCCESS [  6.455 s]
[INFO] CredentialProvider ................................. SUCCESS [ 11.368 s]
[INFO] Frank Management Gateway ........................... SUCCESS [  6.904 s]
[INFO] Frank!Framework DBMS ............................... SUCCESS [  4.012 s]
[INFO] Frank!Framework core ............................... SUCCESS [07:28 min]
[INFO] Frank Console ...................................... SUCCESS [  0.226 s]
[INFO] Frank Console Backend .............................. SUCCESS [ 13.083 s]
[INFO] Frank Console Frontend ............................. SUCCESS [01:29 min]
[INFO] Frank Console Webapp ............................... SUCCESS [  4.872 s]
[INFO] Frank!Framework Larva .............................. SUCCESS [  6.218 s]
[INFO] Frank!Framework Ladybug ............................ SUCCESS [  6.077 s]
[INFO] Frank!Framework minimal bundle ..................... SUCCESS [  0.368 s]
[INFO] Frank!Framework support for Akamai ................. SUCCESS [  9.763 s]
[INFO] Frank!Framework support for AWS .................... FAILURE [ 21.338 s]
[INFO] Frank!Framework support for Batch processing ....... SKIPPED
[INFO] Frank!Framework support for Cmis ................... SKIPPED
[INFO] Frank!Framework support for Aspose ................. SKIPPED
[INFO] Special classes for NN ............................. SKIPPED
[INFO] Frank!Framework support for Messaging Systems ...... SKIPPED
[INFO] Frank!Framework full bundle ........................ SKIPPED
[INFO] Frank!Framework webapp ............................. SKIPPED
[INFO] Frank!Framework Test ............................... SKIPPED
[INFO] Frank!Framework example ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:53 min
[INFO] Finished at: 2024-01-25T10:11:03+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "proprietary" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project frankframework-aws: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\martijn\git\frankframework\aws\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :frankframework-aws

C:\Users\martijn\git\frankframework>
```

**Comment by nielsm5** [comment]
Strange.. The error (not being able to find org.junit.rules.TestName) implies that we use that class somewhere, but I cannot see it being used anywhere in our code!
We're trying to migrate away from all JUnit 4 classes in order to avoid these type of problems. If you add `-PL AWS` it should ignore the AWS module for now.

**Comment by mhdirkse** [comment]
I tried `mvn -P!proprietary --projects !aws clean install` but now the file system errors are back. I have this:

```
[INFO] Running org.frankframework.xslt.XsltSenderTest
[WARNING] Tests run: 41, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.352 s - in org.frankframework.xslt.XsltSenderTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestCopyFile:320 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestExistsMethod:355 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestGetParentOfTheDeletedFile:572 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileFromEmptyFolder:471->BasicFileSystemTest.basicFileSystemTestListFile:368 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot:480->BasicFileSystemTest.basicFileSystemTestListFile:368 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromRootWhenReadingFromFolder:497->BasicFileSystemTest.basicFileSystemTestListFile:368 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestModificationTime:225 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestMoveFile:249 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestNotExists:77 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestReadSpecialCharsFails:190 » FileSystem
[INFO]
[ERROR] Tests run: 4865, Failures: 0, Errors: 10, Skipped: 290
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Frank!Framework parent 8.1.0-SNAPSHOT:
[INFO]
[INFO] Frank!Framework parent ............................. SUCCESS [  7.972 s]
[INFO] Frank!Framework Commons ............................ SUCCESS [ 13.107 s]
[INFO] Frank!Framework Security ........................... SUCCESS [  6.231 s]
[INFO] CredentialProvider ................................. SUCCESS [ 12.467 s]
[INFO] Frank Management Gateway ........................... SUCCESS [  7.162 s]
[INFO] Frank!Framework DBMS ............................... SUCCESS [  4.113 s]
[INFO] Frank!Framework core ............................... FAILURE [08:16 min]
[INFO] Frank Console ...................................... SKIPPED
[INFO] Frank Console Backend .............................. SKIPPED
[INFO] Frank Console Frontend ............................. SKIPPED
[INFO] Frank Console Webapp ............................... SKIPPED
[INFO] Frank!Framework Larva .............................. SKIPPED
[INFO] Frank!Framework Ladybug ............................ SKIPPED
[INFO] Frank!Framework minimal bundle ..................... SKIPPED
[INFO] Frank!Framework support for Akamai ................. SKIPPED
[INFO] Frank!Framework support for Batch processing ....... SKIPPED
[INFO] Frank!Framework support for Cmis ................... SKIPPED
[INFO] Frank!Framework support for Aspose ................. SKIPPED
[INFO] Special classes for NN ............................. SKIPPED
[INFO] Frank!Framework support for Messaging Systems ...... SKIPPED
[INFO] Frank!Framework full bundle ........................ SKIPPED
[INFO] Frank!Framework webapp ............................. SKIPPED
[INFO] Frank!Framework Test ............................... SKIPPED
[INFO] Frank!Framework example ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:07 min
[INFO] Finished at: 2024-02-01T11:19:47+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "proprietary" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project frankframework-core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\martijn\git\frankframework\core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :frankframework-core

C:\Users\martijn\git\frankframework>
```

It strikes me that profile `proprietary` could not be found because it appears in the parent pom.xml.

**Comment by jkosternl** [comment]
1. @mhdirkse, I am using Java `11.0.20.1` and Maven version `3.9.3`. Can you try using that? 
1. Tip: you don't need to do `install` on maven. Just run `mvn clean test` to get the same results. 
1. Perhaps clean your local maven cache partly (`~/.m2/repository/org/frankframework/`), if you think things are corrupted. All unit tests in master should just run fine. 
1. The profile `proprietary` is defined in the root `pom.xml` file. When that can not be found, that's an error for sure. Perhaps that's solved when you upgrade your maven?

**Comment by mhdirkse** [comment]
Thanks. The tests still fail after erasing my .m2/repository folder. I have:

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestCopyFile:320 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestExistsMethod:355 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestGetParentOfTheDeletedFile:572 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileFromEmptyFolder:471->BasicFileSystemTest.basicFileSystemTestListFile:368 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFolders:508 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromOtherFoldersWhenReadingFromRoot:480->BasicFileSystemTest.basicFileSystemTestListFile:368 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestListFileShouldNotReadFromRootWhenReadingFromFolder:497->BasicFileSystemTest.basicFileSystemTestListFile:368 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestModificationTime:225 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestMoveFile:249 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestNotExists:77 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestReadSpecialChars:172 » FileSystem
[ERROR]   Samba1FileSystemTest>BasicFileSystemTest.basicFileSystemTestReadSpecialCharsFails:190 » FileSystem
[INFO]
[ERROR] Tests run: 4846, Failures: 0, Errors: 12, Skipped: 291
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Frank!Framework parent 8.1.0-SNAPSHOT:
[INFO]
[INFO] Frank!Framework parent ............................. SUCCESS [ 31.264 s]
[INFO] Frank!Framework Commons ............................ SUCCESS [ 24.781 s]
[INFO] Frank!Framework Security ........................... SUCCESS [ 12.325 s]
[INFO] CredentialProvider ................................. SUCCESS [ 19.468 s]
[INFO] Frank Management Gateway ........................... SUCCESS [ 11.912 s]
[INFO] Frank!Framework DBMS ............................... SUCCESS [  3.862 s]
[INFO] Frank!Framework core ............................... FAILURE [10:15 min]
[INFO] Frank Console ...................................... SKIPPED
[INFO] Frank Console Backend .............................. SKIPPED
[INFO] Frank Console Frontend ............................. SKIPPED
[INFO] Frank Console Webapp ............................... SKIPPED
[INFO] Frank!Framework Larva .............................. SKIPPED
[INFO] Frank!Framework Ladybug ............................ SKIPPED
[INFO] Frank!Framework minimal bundle ..................... SKIPPED
[INFO] Frank!Framework support for Akamai ................. SKIPPED
[INFO] Frank!Framework support for AWS .................... SKIPPED
[INFO] Frank!Framework support for Batch processing ....... SKIPPED
[INFO] Frank!Framework support for Cmis ................... SKIPPED
[INFO] Frank!Framework support for Aspose ................. SKIPPED
[INFO] Special classes for NN ............................. SKIPPED
[INFO] Frank!Framework support for Messaging Systems ...... SKIPPED
[INFO] Frank!Framework full bundle ........................ SKIPPED
[INFO] Frank!Framework webapp ............................. SKIPPED
[INFO] Frank!Framework Test ............................... SKIPPED
[INFO] Frank!Framework example ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:59 min
[INFO] Finished at: 2024-02-05T16:56:09+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project frankframework-core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\martijn\git\frankframework\core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :frankframework-core

C:\Users\martijn\git\frankframework>
```

```
C:\Users\martijn\git\frankframework>mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Users\martijn\Programmas\apache-maven-3.9.6-bin\apache-maven-3.9.6
Java version: 11.0.22, vendor: Eclipse Adoptium, runtime: C:\Users\martijn\Programmas\OpenJDK11U-jdk_x64_windows_hotspot_11.0.22_7\jdk-11.0.22+7
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

C:\Users\martijn\git\frankframework>
```

The command `mvn help:active-profiles` shows:

```
The following profiles are active:

 - proprietary (source: external)
 - default-modules (source: org.frankframework:frankframework-parent:${revision})
 - proprietary (source: org.frankframework:frankframework-parent:${revision})
```

**Comment by jkosternl** [comment]
Thanks for trying out. Too bad it didn't work out. TIp: you don't need to flush your whole M2 repo, just the `org/frankframework` part should suffice, but maybe in this strange situation, it was just fine. 
I am wondering what is going on. Can you do one more tryout? I was thinking of a fresh `git clone` of the frankframework-repo and then building that with `mvn test`. Just to make sure nothing from the past is sitting in the way. 
I also just noticed that your first experiments could build `core` but in the last experiment, it was failing at `core`. That makes it even more weird.

**Comment by jkosternl** [comment]
TIm had vandaag precies dezelfde errors op zijn laptop, begreep ik. We weten nog niet waarom dit wel door onze CI/CD is gegaan. Zijn er nog mee bezig. Als dat opgelost is, kun je tzt effe een pull doen en die build opnieuw starten. Dan moeten die testen wel werken.

**Comment by jkosternl** [comment]
Oke, mijn conclusies hierboven blijken niet valide te zijn. Tim schrijft vanmorgen namelijk: "Bij mij gisteren waren het niet altijd dezelfde tests en na herstarten laptop ging alles weer goed." Ik neem aan dat dit bij Martijn niet het probleem oplost en dus blijft het zo helaas toch een mysterie.

**Comment by mhdirkse** [comment]
I just ran the unit tests for the first time with Java 17, after pulling. I have commit 9e5a9b6b65d87d7478f42e93467353fbde72d2ee now. This way the build succeeded. I am curious whether I was lucky or whether the issue has been fixed.

**Comment by mhdirkse** [comment]
I mean: running the tests was successfull. I did mvn test.

**Comment by mhdirkse** [comment]
I just tried with Java 21. Now I have the following error:

```
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   FtpFileSystemTest>FileSystemTest.writableFileSystemTestCopyFileToNonExistentDirectoryCreateFolderTrue:568 » FileSystem
[INFO]
[ERROR] Tests run: 4947, Failures: 0, Errors: 1, Skipped: 128
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Frank!Framework parent 8.1.0-SNAPSHOT:
```

I scrolled up to find more details:

```
[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.171 s - in org.frankframework.filesystem.FtpFileSystemSenderTest
[INFO] Running org.frankframework.filesystem.FtpFileSystemTest
[ERROR] Tests run: 51, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 170.063 s <<< FAILURE! - in org.frankframework.filesystem.FtpFileSystemTest
[ERROR] writableFileSystemTestCopyFileToNonExistentDirectoryCreateFolderTrue  Time elapsed: 120.424 s  <<< ERROR!
org.frankframework.filesystem.FileSystemException: Cannot connect to the FTP server with domain [localhost]: (IOException) Timed out waiting for initial connect reply: (SocketTimeoutException) Read timed out
Caused by: java.io.IOException: Timed out waiting for initial connect reply
Caused by: java.net.SocketTimeoutException: Read timed out

[INFO] Running org.frankframework.filesystem.LocalFileSystemActorTest
[INFO] Tests run: 71, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.574 s - in org.frankframework.filesystem.LocalFileSystemActorTest
```

**Comment by nielsm5** [comment]
Closing this as it seems to be a fluke. A new issue can be opened when there are test failures.

**Comment by mhdirkse** [comment]
I still have this issue on the following commit:

```
commit 30ef8c8fd4146a9624d0edfc95f33a16990ee0d3 (HEAD -> master, origin/master, origin/HEAD)
Author: Niels Meijer <nielsmeijer@hotmail.com>
Date:   Tue Mar 12 15:38:47 2024 +0100

    Support Ladybug database storage (#6385)
```

I built with Java 17 and got the following errors:

```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 s - in org.frankframework.filesystem.mock.MockForEachAttachmentPipeTest
[INFO] Running org.frankframework.filesystem.SftpFileSystemActorTest
[ERROR] Tests run: 67, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.924 s <<< FAILURE! - in org.frankframework.filesystem.SftpFileSystemActorTest
[ERROR] fileSystemActorMoveActionTestRootToFolderExistsAndAllowToCreate  Time elapsed: 0.005 s  <<< ERROR!
java.net.BindException: Address already in use: bind
        at org.frankframework.filesystem.SftpFileSystemActorTest.setUp(SftpFileSystemActorTest.java:44)

[INFO] Running org.frankframework.filesystem.SftpFileSystemSenderTest
[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.063 s - in org.frankframework.filesystem.SftpFileSystemSenderTest
[INFO] Running org.frankframework.filesystem.SftpFileSystemTest
[ERROR] Tests run: 56, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.638 s <<< FAILURE! - in org.frankframework.filesystem.SftpFileSystemTest
[ERROR] writableFileSystemTestCreateNewFile  Time elapsed: 0.002 s  <<< ERROR!
java.net.BindException: Address already in use: bind
        at org.frankframework.filesystem.SftpFileSystemTest.startNewSshDaemon(SftpFileSystemTest.java:51)
        at org.frankframework.filesystem.SftpFileSystemTest.setUp(SftpFileSystemTest.java:41)

[INFO] Running org.frankframework.filesystem.smb.Samba1FileSystemActorTest
```

In the summary near the end of the Maven build I had:

```
[INFO] Frank!Framework FileSystems ........................ FAILURE [05:06 min]
```

And below that the errors were summarized as follows:

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project frankframework-filesystem: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\martijn\git\frankframework\filesystem\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
```

**Comment by jkosternl** [comment]
> I still have this issue on the following commit:

Hi @mhdirkse, likely this is not related. I've randomized the bind ports for the local SFTP server, but it also still sometimes fails at GitHub builds. I am now working on a fix. Please ignore these errors for now.

**Comment by nielsm5** [comment]
The sftp server should automatically find an unused port. @jkosternl your solution by doing exactly the same won't fix this. I've personally never seen this fail on GH by the way...

**Comment by jkosternl** [comment]
> The sftp server should automatically find an unused port. @jkosternl your solution by doing exactly the same won't fix this. I've personally never seen this fail on GH by the way...

Some evidence: https://github.com/frankframework/frankframework/actions/runs/8251487224/job/22568642354
My solution just tries a few ports, in order to pass through a free one to the SFTP server. This increases the chances that it works.

**Comment by nielsm5** [comment]
Nu het pr er door is, zou je het nogmaals kunnen proberen?

**Comment by mhdirkse** [comment]
Gelukt, de testen slagen als ik met Java 17 bouw. Ik heb met deze commit getest:

```
commit bb172e86db48ab54629e104f7e42807343574a01 (HEAD -> master, origin/master, origin/HEAD)
Author: MarkvdVorst <34445874+MarkvdVorst@users.noreply.github.com>
Date:   Wed Mar 13 17:39:45 2024 +0100

    Remove unnecessary information from GrayBox view (#6371)
```

**Comment by jkosternl** [comment]
> Gelukt, de testen slagen als ik met Java 17 bouw. Ik heb met deze commit getest:

Great! Than likely the new SFTP-unit tests work fine, in finding a free port. I'll close the issue again.
