### ISSUE TITLE
Configuration Version History is broken

### ISSUE THREAD

**Issue by philipsens** [frankframework/frankframework#6116]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I can't see the versions of the uploaded configuration.

**Reporter**
@philipsens 

**To Reproduce**
1. Upload a configuration
2. Go to manage configurations
3. Click on the uploaded configuration

**Screenshots**
![image](https://github.com/frankframework/frankframework/assets/12416423/47131aed-63d6-4906-83d9-0a59512b4230)

**Environment**
```
FF! 8.1.0-20231223.223430: frank2example2
Running on frank2example2-6466d57d8c-9bm7b using Apache Tomcat/9.0.83
Java Version: OpenJDK Runtime Environment (11.0.21+9)
Heap size: 140M, total JVM memory: 4096M
Free disk space: 208GB, total disk space: 501GB
Up since: 2024-01-16 13:59:28 (1m) 
```

**Additional Environment**
Running on K8s

**Additional Context**
Browser log:
```javascript ERROR 
Object { headers: {…}, status: 400, statusText: "OK", url: "http://localhost:58162/iaf/api/configurations/testKeystore/versions", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://localhost:58162/iaf/api/configurations/testKeystore/versions: 400 OK", error: {…} }
​
error: Object { status: "Bad Request", error: "unable to retrieve configuration from database: (UnsupportedOperationException)" }
​​
error: "unable to retrieve configuration from database: (UnsupportedOperationException)"
​​
status: "Bad Request"
​​
<prototype>: Object { … }
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit() }
​
message: "Http failure response for http://localhost:58162/iaf/api/configurations/testKeystore/versions: 400 OK"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 400
​
statusText: "OK"
​
url: "http://localhost:58162/iaf/api/configurations/testKeystore/versions"
​
<prototype>: Object { … }
main.c5942efef8d5e9c6.js:1:51506
```

Application log:
```console frank2example2.log
2024-01-16 13:09:10,678 ERROR [http-nio-8080-exec-8] {} bus.BusException - unable to retrieve configuration from database
java.lang.UnsupportedOperationException: null
      at java.sql/java.sql.Date.toInstant(Unknown Source) ~[java.sql:?]
      at org.frankframework.util.DateFormatUtils.format(DateFormatUtils.java:138) ~[frankframework-commons-8.1.0-20231223.223430.jar:?]
      at org.frankframework.management.bus.dto.ConfigurationDTO.setDatabaseAttributes(ConfigurationDTO.java:94) ~[frankframework-core-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.frankframework.management.bus.endpoints.ConfigManagement.getConfigsFromDatabase(ConfigManagement.java:245) ~[frankframework-core-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.frankframework.management.bus.endpoints.ConfigManagement.getConfigurationDetailsByName(ConfigManagement.java:95) ~[frankframework-core-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at jdk.internal.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) ~[?:?]
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      ...
      at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.31.jar:5.3.31]
      ... suppressed 9 lines
      at org.springframework.messaging.MessageChannel.send(MessageChannel.java:45) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) [spring-messaging-5.3.31.jar:5.3.31]
      ... suppressed 8 lines
      at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:222) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:178) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:233) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:47) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:46) [spring-messaging-5.3.31.jar:5.3.31]
      at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:97) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:521) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceiveMessage(MessagingGatewaySupport.java:491) [spring-integration-core-5.5.20.jar:5.5.20]
      at org.frankframework.management.bus.LocalGateway.sendSyncMessage(LocalGateway.java:41) [frankframework-management-gateway-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.frankframework.management.web.FrankApiBase.sendSyncMessage(FrankApiBase.java:76) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.frankframework.management.web.FrankApiBase.callSyncGateway(FrankApiBase.java:94) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.frankframework.management.web.FrankApiBase.callSyncGateway(FrankApiBase.java:90) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.frankframework.management.web.ShowConfiguration.getConfigurationDetailsByName(ShowConfiguration.java:144) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
      ...
      at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.6.2.jar:3.6.2]
      at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.6.2.jar:3.6.2]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.6.2.jar:3.6.2]
      at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.6.2.jar:3.6.2]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.6.2.jar:3.6.2]
      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.6.2.jar:3.6.2]
      at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.frankframework.management.web.ServletDispatcher.invoke(ServletDispatcher.java:91) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) [servlet-api.jar:4.0.FR]
      at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [cxf-rt-transports-http-3.6.2.jar:3.6.2]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [catalina.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.83]
      at org.frankframework.web.filters.CacheControlFilter.doFilter(CacheControlFilter.java:51) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.83]
      at org.frankframework.web.filters.CorsFilter.doFilter(CorsFilter.java:111) [frankframework-console-backend-8.1.0-20231223.223430.jar:8.1.0-20231223.223430]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.83]
      ... suppressed 17 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.31.jar:5.3.31]
      ... suppressed 5 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.31.jar:5.3.31]
      ... suppressed 2 lines
      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.31.jar:5.3.31]
      ... suppressed 3 lines
      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.31.jar:5.3.31]
      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.31.jar:5.3.31]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.83]
      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.83]
      at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:70) [log4j-web-2.22.0.jar:2.22.0]
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.83]
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.83]
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [catalina.jar:9.0.83]
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:9.0.83]
      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:596) [catalina.jar:9.0.83]
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.83]
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.83]
      at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670) [catalina.jar:9.0.83]
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.83]
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:9.0.83]
      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-coyote.jar:9.0.83]
      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.83]
      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) [tomcat-coyote.jar:9.0.83]
      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) [tomcat-coyote.jar:9.0.83]
      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.83]
      at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.83]
      at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.83]
      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.83]
      at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by philipsens** [comment]
> From first sight it looks like it has more to do with the framework rather than the console. The configuration seems to upload without issue given back to the console, only after a reload does it give an error when trying to get the configuration version.
> 
> The current frontend (master) works fine with an older ff backend (7.8.4) so there is nothing more that I can do from a console standpoint. The only thing that I can fix is showing the correct name instead of `[Object object]`.

That's right. I think it had to do with @tnleeuw changing a lot of the date formatting to Instant (#5854). I think this one slipped past him.

**Comment by Matthbo** [comment]
Finally found the issue. It does not just have to do with using Instant instead of Date but the `rs.getDate` on ConfigManagement.java:244 fails because its not a DATE column but a TIMESTAMP column
![image](https://github.com/frankframework/frankframework/assets/4380412/4708d8a8-062b-452c-8d70-0f115629d2f5)

The sql error in the logs are caused by java.sql.Date not being able to convert a TIMESTAMP to a date
