### ISSUE TITLE
Mermaid broken

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6197]
**Describe the issue**
When I enable Mermaid it doesn't work

**Reporter**
Jaco de Groot

**To Reproduce**
1. Add flow.generator=org.frankframework.util.flow.MermaidFlowGenerator to DeploymentSpecifics.properties of Frank2Example3 (or another example) of the Frank!Runner
2. Start Frank2Example3
3. Open the main page of the console
4. See NO IMAGE AVAILABLE at every adapter
5. See the following stacktrace in the logging:

```
2024-01-31 14:19:22,176 WARN [main] {} flow.FlowDiagramManager - failed to initalize FlowGenerator
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.frankframework.util.flow.MermaidFlowGenerator': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/sap/conn/jco/JCoException
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.frankframework.util.SpringUtils.createBean(SpringUtils.java:26) ~[frankframework-commons-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.util.flow.FlowDiagramManager.createFlowGenerator(FlowDiagramManager.java:94) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.util.flow.FlowDiagramManager.afterPropertiesSet(FlowDiagramManager.java:73) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByName(AbstractAutowireCapableBeanFactory.java:1471) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.frankframework.util.SpringUtils.createBean(SpringUtils.java:26) ~[frankframework-commons-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.management.bus.MessageDispatcher.findServiceActivators(MessageDispatcher.java:101) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.management.bus.MessageDispatcher.afterPropertiesSet(MessageDispatcher.java:71) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929) [spring-context-5.3.31.jar:5.3.31]
      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) [spring-context-5.3.31.jar:5.3.31]
      at org.frankframework.lifecycle.IbisApplicationContext.createApplicationContext(IbisApplicationContext.java:105) [frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.configuration.IbisContext.init(IbisContext.java:116) [frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.configuration.IbisContext.init(IbisContext.java:96) [frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.lifecycle.FrankApplicationInitializer.onStartup(FrankApplicationInitializer.java:85) [frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174) [spring-web-5.3.31.jar:5.3.31]
      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4904) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1186) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1941) [catalina.jar:9.0.84]
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) [?:?]
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
      at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.84]
      at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) [?:?]
      at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1096) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1619) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.84]
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
      at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.84]
      at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) [?:?]
      at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.84]
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
      ...
      at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) [bootstrap.jar:9.0.84]
      at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) [bootstrap.jar:9.0.84]
Caused by: java.lang.NoClassDefFoundError: com/sap/conn/jco/JCoException
      at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
      at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
      at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
      at org.frankframework.util.flow.MermaidFlowGenerator.compileFrankElementList(MermaidFlowGenerator.java:100) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.util.flow.MermaidFlowGenerator.afterPropertiesSet(MermaidFlowGenerator.java:86) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      ... 76 more
Caused by: java.lang.ClassNotFoundException: com.sap.conn.jco.JCoException
      at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329) ~[catalina.jar:9.0.84]
      at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141) ~[catalina.jar:9.0.84]
      at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
      at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
      at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
      at org.frankframework.util.flow.MermaidFlowGenerator.compileFrankElementList(MermaidFlowGenerator.java:100) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.frankframework.util.flow.MermaidFlowGenerator.afterPropertiesSet(MermaidFlowGenerator.java:86) ~[frankframework-core-8.1.0-20240130.192323.jar:8.1.0-20240130.192323]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      ... 76 more
```

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 8.1.0-20240130.192323: Frank2Example3
Running on xxx using Apache Tomcat/9.0.84
Java Version: OpenJDK Runtime Environment (21.0.1+12-LTS)
Heap size: 163M, total JVM memory: 237M
Free disk space: 23GB, total disk space: 475GB
Up since: 2024-01-31 14:19:18 (24m) 
```

**Additional Environment**
 - DBMS: H2
 - Browser: Firefox

**Additional Context**
\-

**Comment by jacodg** [comment]
Did a new test with 8.1.0-20240201.192326 and it still fails. First I see two times the following stacktrace:

```
2024-02-02 09:56:19,498 INFO [main] {} flow.MermaidFlowGenerator - Found class [org.frankframework.extensions.sap.jco3.SapLUWManager] on classpath which cannot be loaded due to exception
java.lang.NoClassDefFoundError: com/sap/conn/jco/JCoException
      at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
      at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
      at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
      at org.frankframework.util.flow.MermaidFlowGenerator.compileFrankElementList(MermaidFlowGenerator.java:102) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
```

This is on INFO level and should not be a problem. But please consider to do it on DEBUG level as in production systems we like to have clean logfiles. Or even better, do not print the entire stacktrace as my estimation is that in 99% of the cases a class like JCoException will not be available. So when searching for errors in the logfile you will always see them and have to remember yourself they can be skipped.

Next the following exception occurs which I suppose is the cause of Mermaid still failing to work:

```
2024-02-02 09:56:19,539 WARN [main] {} flow.FlowDiagramManager - failed to initalize FlowGenerator
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.frankframework.util.flow.MermaidFlowGenerator': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/sap/conn/jco/JCoFunction
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.frankframework.util.SpringUtils.createBean(SpringUtils.java:26) ~[frankframework-commons-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.util.flow.FlowDiagramManager.createFlowGenerator(FlowDiagramManager.java:94) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.util.flow.FlowDiagramManager.afterPropertiesSet(FlowDiagramManager.java:73) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByName(AbstractAutowireCapableBeanFactory.java:1471) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.frankframework.util.SpringUtils.createBean(SpringUtils.java:26) ~[frankframework-commons-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.management.bus.MessageDispatcher.findServiceActivators(MessageDispatcher.java:101) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.management.bus.MessageDispatcher.afterPropertiesSet(MessageDispatcher.java:71) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) [spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929) [spring-context-5.3.31.jar:5.3.31]
      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) [spring-context-5.3.31.jar:5.3.31]
      at org.frankframework.lifecycle.IbisApplicationContext.createApplicationContext(IbisApplicationContext.java:105) [frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.configuration.IbisContext.init(IbisContext.java:116) [frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.configuration.IbisContext.init(IbisContext.java:96) [frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.lifecycle.FrankApplicationInitializer.onStartup(FrankApplicationInitializer.java:85) [frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174) [spring-web-5.3.31.jar:5.3.31]
      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4904) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1186) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1941) [catalina.jar:9.0.84]
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) [?:?]
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
      at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.84]
      at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) [?:?]
      at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1096) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1619) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.84]
      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.84]
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
      at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.84]
      at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) [?:?]
      at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921) [catalina.jar:9.0.84]
      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.84]
      at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.84]
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
      ...
      at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) [bootstrap.jar:9.0.84]
      at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) [bootstrap.jar:9.0.84]
Caused by: java.lang.NoClassDefFoundError: com/sap/conn/jco/JCoFunction
      at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
      at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
      at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) ~[?:?]
      at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3609) ~[?:?]
      at java.base/java.lang.Class.getMethods(Class.java:2185) ~[?:?]
      at org.frankframework.util.flow.MermaidFlowGenerator.compileFrankElementList(MermaidFlowGenerator.java:116) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.util.flow.MermaidFlowGenerator.afterPropertiesSet(MermaidFlowGenerator.java:86) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      ... 76 more
Caused by: java.lang.ClassNotFoundException: com.sap.conn.jco.JCoFunction
      at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329) ~[catalina.jar:9.0.84]
      at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141) ~[catalina.jar:9.0.84]
      at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
      at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
      at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) ~[?:?]
      at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3609) ~[?:?]
      at java.base/java.lang.Class.getMethods(Class.java:2185) ~[?:?]
      at org.frankframework.util.flow.MermaidFlowGenerator.compileFrankElementList(MermaidFlowGenerator.java:116) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.frankframework.util.flow.MermaidFlowGenerator.afterPropertiesSet(MermaidFlowGenerator.java:86) ~[frankframework-core-8.1.0-20240201.192326.jar:8.1.0-20240201.192326]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar:5.3.31]
      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar:5.3.31]
      ... 76 more
```
