### ISSUE TITLE
JavascriptSender throws "1 Object(s) still exist in runtime" error

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6238]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Seems that this error is in some way linked to the return of the javascript function. I suspect it throws this error whenever the return is not a string. From what I read while troubleshooting, the actual error is thrown because the JNI handle for the return from a function is not automatically released.

Would be nice if the framework would attempt to convert it to a string if that is a strict requirement or otherwise at least a more descriptive error that point towards the actual problem.

**Reporter**
M. Lenterman

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input thats work fine**
```
function test(obj) {
    json = JSON.parse(obj);
    return JSON.stringify(json);
}
```
**Input that throws the error**
```
function test(obj) {
    return JSON.parse(obj);
}
```

**Environment**
```
FF! 8.1.0-20240111.192324: Openforms2bpel 1.0.0
Running on 00ec8e5bbf7c using Apache Tomcat/9.0.83
Java Version: OpenJDK Runtime Environment (11.0.22+7)
Heap size: 546M, total JVM memory: 1056M
Free disk space: 202GB, total disk space: 251GB
Up since: 2024-02-05 15:22:15 (18h) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
```
java.lang.IllegalStateException: 1 Object(s) still exist in runtime
at com.eclipsesource.v8.V8.release(V8.java:302)
at org.frankframework.javascript.J2V8.closeRuntime(J2V8.java:93)
at org.frankframework.senders.JavascriptSender.sendMessage(JavascriptSender.java:166)
at org.frankframework.senders.JavascriptSender$$FastClassBySpringCGLIB$$e81a732a.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugSenderInputOutputAbort(IbisDebuggerAdvice.java:235)
at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugSenderInputOutputAbort(IbisDebuggerAdvice.java:288)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by nielsm5** [comment]
We're rethrowing the exception because there is a memory leak. There is no way we can automatically detect if the function has a return type, nor a way to convert this. The return type is not the only ObjectReference, so we cannot say 'change the return type to String' for example.

**Comment by tnleeuw** [comment]
@MLenterman Do you have for us a small testcase with which we can easily reproduce the problem in a unit-test?

**Comment by tnleeuw** [comment]
@MLenterman Next step: I can fix the problem, but the output is not what you want.
Because right now, the output is `[object Object]` and not your JSON object, nor a string representation of it.

Returning an array is fine, as long as it's an array of objects that can be converted.

**Comment by tnleeuw** [comment]
I have made a draft PR: https://github.com/frankframework/frankframework/pull/6301

But since the result produced now is not useful the issue remains on hold.

@MLenterman If you have a better way to turn the answer into a useful result-object, be our guest!
