### ISSUE TITLE
(MalformedByteSequenceException) Invalid byte 2 of 3-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6280]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Getting an xml as a response of http call. The xml does not have xml declaration. It is probably encoded with iso-8859-1 as we see the following in the logs.

```
http.HttpSender - retrieved result [context:
Server: Web asQit Forker (WAF/2.05); Microsoft-HTTPAPI/2.0
Date: Wed, 14 Feb 2024 16:15:07 GMT
Content-Length: 1845
Metadata.Charset: ISO-8859-1
```

However, it is being parsed with utf-8

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 50; Invalid byte 2 of 3-byte UTF-8 sequence.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	... 147 more
Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 2 of 3-byte UTF-8 sequence.
	at org.apache.xerces.impl.io.UTF8Reader.invalidByte(Unknown Source)
	at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
	at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
	at org.apache.xerces.impl.XMLEntityScanner.peekChar(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(Unknown Source)
	... 155 more
```

Details were shared with @tnleeuw 

**Reporter**
Ali

FF: 7.9.0-hotfix7

**Comment by nielsm5** [comment]
Strange, it looks like the sender is reads the charset property, but it's not used?
Could you give us a bit more context how you're reading the response? Directly as xsltpipe input of as parameter?

**Comment by jjansenvr** [comment]
The system sending the response is not working according to the XML specs. The XML declaration is mandatory when the input is not UTF-8 or UTF-16. 

In our case the incoming stream is passed to the parser, passing by the auto detection? 

The workaround we/Ali implemented seems to work because concatenating a xml declaration to the incoming stream transforms the stream to a string (in this process the auto detect also takes the iso encoding into account)

**Comment by tnleeuw** [comment]
Reopening the issue because we still need to forward-port it to 8.0, master.
