### ISSUE TITLE
Support rowversion datatype in mssql

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#7333]
### Current Behavior

when selecting from a mssql table that has a rowversion column following error is thrown

_Stacktrace below_

Also, despite this error the pipeline succeeds and it looks like there is only one row returned. But it could be that there are more rows.

https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver16

### Expected Behavior

1. when selecting a rowversion column that the value is properly shown
2. when such errors occurs that the pipeline fails

### Environment Information

**FF! 8.3.0-20240813.042338**: Frank2Eekels 1.0.0
Running on **836e396f856e** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (17.0.11+9)**
Heap size: **349.5 MiB**, total JVM memory: **471.0 MiB**
Free memory: **121.5 MiB**, max memory: **1.9 GiB**
Free disk space: **18.8 GiB**, total disk space: **58.4 GiB**

### Steps To Reproduce

1. run attached config
2. see success in ladybug (select step/pipe)
3. see error in log

### Configuration

```xml
<Module
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FrankConfig.xsd"
>
    <Adapter name="test">
        <Receiver>
            <JavaListener name="test" />
        </Receiver>
        <Pipeline>
            <SenderPipe name="create">
                <FixedQuerySender datasourceName="jdbc/frank2eekels-eureka-loc" query="CREATE TABLE MyTest (myKey int, myValue int, RV rowversion)"/>

                <Forward name="exception" path="insert" />
            </SenderPipe>

            <SenderPipe name="insert">
                <FixedQuerySender datasourceName="jdbc/frank2eekels-eureka-loc" query="INSERT INTO MyTest (myKey, myValue) VALUES (1, 0)"></FixedQuerySender>
            </SenderPipe>

            <SenderPipe name="select">
                <FixedQuerySender datasourceName="jdbc/frank2eekels-eureka-loc" queryType="SELECT" query="SELECT * FROM MyTest" prettyPrint="true"></FixedQuerySender>
            </SenderPipe>
        </Pipeline>
    </Adapter>
</Module>
```

### Input

any input

### What database are you using?

MSSQL

### What browsers are you seeing the problem on?

Firefox

### Relevant Log Output

```console
2024-08-15 12:20:50,362 ERROR [http-nio-8080-exec-6] {mid=testmessageac130003-4ee30f0c_1915584b9a9_-7ff9, cid=Test a Pipeline 7, adapter=test, pipe=select} util.DB2XMLWriter - Error occurred at row [0]
org.frankframework.core.SenderException: error getting fieldvalue column [3] fieldType [BINARY]: (SQLServerException) The conversion from timestamp to BLOB is unsupported.
	at org.frankframework.util.DB2XMLWriter.getRowXml(DB2XMLWriter.java:345) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	at org.frankframework.util.DB2XMLWriter.processResultSet(DB2XMLWriter.java:249) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	at org.frankframework.util.DB2XMLWriter.getXML(DB2XMLWriter.java:132) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	at org.frankframework.jdbc.JdbcQuerySenderBase.getResult(JdbcQuerySenderBase.java:522) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.jdbc.JdbcQuerySenderBase.executeSelectQuery(JdbcQuerySenderBase.java:636) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.jdbc.JdbcQuerySenderBase.executeSelectQuery(JdbcQuerySenderBase.java:621) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.jdbc.JdbcQuerySenderBase.executeStatementSet(JdbcQuerySenderBase.java:331) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.jdbc.FixedQuerySender.sendMessage(FixedQuerySender.java:101) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at jdk.internal.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugSenderInputOutputAbort(IbisDebuggerAdvice.java:222) ~[frankframework-ladybug-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugBlockEnabledSenderInputOutputAbort(IbisDebuggerAdvice.java:286) ~[frankframework-ladybug-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at jdk.internal.reflect.GeneratedMethodAccessor179.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 10 lines
	at org.frankframework.jdbc.FixedQuerySender$$SpringCGLIB$$0.sendMessage(<generated>) ~[?:?]
	at org.frankframework.jdbc.JdbcSenderBase.sendMessage(JdbcSenderBase.java:138) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.pipes.MessageSendingPipe.sendMessage(MessageSendingPipe.java:754) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.pipes.MessageSendingPipe.sendMessageWithRetries(MessageSendingPipe.java:504) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:435) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	... suppressed 15 lines
	at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:178) ~[frankframework-ladybug-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 18 lines
	at jdk.internal.reflect.GeneratedMethodAccessor175.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:151) ~[frankframework-ladybug-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at jdk.internal.reflect.GeneratedMethodAccessor174.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 15 lines
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:117) ~[frankframework-ladybug-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 16 lines
	at org.frankframework.core.PipeLine.process(PipeLine.java:389) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.core.Adapter.processMessageWithExceptions(Adapter.java:606) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.core.Adapter.processMessageDirect(Adapter.java:533) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.management.bus.endpoints.TestPipeline.processMessage(TestPipeline.java:111) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.management.bus.endpoints.TestPipeline.runTestPipeline(TestPipeline.java:89) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 5 lines
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.proceed(AuthorizationManagerBeforeMethodInterceptor.java:269) ~[spring-security-core-6.3.1.jar:6.3.1]
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.attemptAuthorization(AuthorizationManagerBeforeMethodInterceptor.java:264) ~[spring-security-core-6.3.1.jar:6.3.1]
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:197) ~[spring-security-core-6.3.1.jar:6.3.1]
	... suppressed 2 lines
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.proceed(AuthorizationManagerBeforeMethodInterceptor.java:269) ~[spring-security-core-6.3.1.jar:6.3.1]
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.attemptAuthorization(AuthorizationManagerBeforeMethodInterceptor.java:264) ~[spring-security-core-6.3.1.jar:6.3.1]
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:197) ~[spring-security-core-6.3.1.jar:6.3.1]
	... suppressed 3 lines
	at org.frankframework.management.bus.endpoints.TestPipeline$$SpringCGLIB$$0.runTestPipeline(<generated>) ~[frankframework-core-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... 
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-6.1.11.jar:6.1.11]
	... 
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-6.1.11.jar:6.1.11]
	... suppressed 10 lines
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-6.1.11.jar:6.1.11]
	... suppressed 10 lines
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:235) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:192) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:390) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:334) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:234) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:47) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:46) ~[spring-messaging-6.1.11.jar:6.1.11]
	at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:107) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:686) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceive(MessagingGatewaySupport.java:614) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceiveMessage(MessagingGatewaySupport.java:587) ~[spring-integration-core-6.3.2.jar:6.3.2]
	at org.frankframework.management.bus.LocalGateway.sendSyncMessage(LocalGateway.java:51) ~[frankframework-management-gateway-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.management.web.FrankApiBase.sendSyncMessage(FrankApiBase.java:43) ~[frankframework-console-backend-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.management.web.TestPipeline.testPipeLine(TestPipeline.java:103) ~[frankframework-console-backend-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... suppressed 5 lines
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.proceed(AuthorizationManagerBeforeMethodInterceptor.java:269) ~[spring-security-core-6.3.1.jar:6.3.1]
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.attemptAuthorization(AuthorizationManagerBeforeMethodInterceptor.java:264) ~[spring-security-core-6.3.1.jar:6.3.1]
	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:197) ~[spring-security-core-6.3.1.jar:6.3.1]
	... suppressed 3 lines
	at org.frankframework.management.web.TestPipeline$$SpringCGLIB$$0.testPipeLine(<generated>) ~[frankframework-console-backend-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	... 
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[servlet-api.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[servlet-api.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[catalina.jar:10.1.24]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-websocket.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[catalina.jar:10.1.24]
	at org.frankframework.web.filters.SecurityLogFilter.doFilterInternal(SecurityLogFilter.java:44) ~[frankframework-console-backend-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.11.jar:6.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[catalina.jar:10.1.24]
	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:107) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.11.jar:6.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[catalina.jar:10.1.24]
	at org.frankframework.web.filters.CacheControlFilter.doFilter(CacheControlFilter.java:50) ~[frankframework-console-backend-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[catalina.jar:10.1.24]
	at org.frankframework.web.filters.CorsFilter.doFilter(CorsFilter.java:111) ~[frankframework-console-backend-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[catalina.jar:10.1.24]
	... suppressed 19 lines
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) [spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.1.11.jar:6.1.11]
	... suppressed 3 lines
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.1.11.jar:6.1.11]
	... suppressed 5 lines
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.1.11.jar:6.1.11]
	... suppressed 2 lines
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.1.11.jar:6.1.11]
	... suppressed 3 lines
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) [spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) [spring-web-6.1.11.jar:6.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [catalina.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) [catalina.jar:10.1.24]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) [catalina.jar:10.1.24]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:10.1.24]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:597) [catalina.jar:10.1.24]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) [catalina.jar:10.1.24]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:10.1.24]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663) [catalina.jar:10.1.24]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:10.1.24]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [catalina.jar:10.1.24]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) [tomcat-coyote.jar:10.1.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:10.1.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) [tomcat-coyote.jar:10.1.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) [tomcat-coyote.jar:10.1.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:10.1.24]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) [tomcat-util.jar:10.1.24]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:10.1.24]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-util.jar:10.1.24]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from timestamp to BLOB is unsupported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:242) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.DataTypes.throwConversionError(DataTypes.java:1118) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValue(dtv.java:3730) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.DTV.getValue(dtv.java:253) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.Column.getValue(Column.java:190) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2105) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2091) ~[mssql-jdbc.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getBlob(SQLServerResultSet.java:2859) ~[mssql-jdbc.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingResultSet.getBlob(DelegatingResultSet.java:341) ~[tomcat-dbcp.jar:10.1.24]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingResultSet.getBlob(DelegatingResultSet.java:341) ~[tomcat-dbcp.jar:10.1.24]
	at org.frankframework.dbms.GenericDbmsSupport.getBlobInputStream(GenericDbmsSupport.java:260) ~[frankframework-dbms-8.3.0-20240813.042338.jar:8.3.0-20240813.042338]
	at org.frankframework.util.JdbcUtil.getBlobInputStream(JdbcUtil.java:251) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	at org.frankframework.util.JdbcUtil.getBlobAsString(JdbcUtil.java:363) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	at org.frankframework.util.JdbcUtil.getValue(JdbcUtil.java:192) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	at org.frankframework.util.DB2XMLWriter.getRowXml(DB2XMLWriter.java:339) ~[frankframework-core-8.3.0-20240813.042338.jar:?]
	... 314 more
```

**Comment by philipsens** [comment]
We need to look into the mapping form binary/blob -> timestamp

**Comment by evandongen** [comment]
Some more background: https://stackoverflow.com/questions/31377666/why-sql-server-timestamp-type-is-mapped-to-binary-type-in-hibernate
