### ISSUE TITLE
acknowledgeMode="client" for jmslistener does not seem to put message back on queue

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#7426]
### Current Behavior

jmslistener configured with acknowledgeMode="client" does not return message to the queue after exception occurs in adapter

### Expected Behavior

adapter returns message to queue when error occurs in adapter.

### Environment Information

**FF! 8.3.0-20240828.042324**: Frank2D 
Running on **[REDACTED]** using **Apache Tomcat/10.1.25**
Java Version: **OpenJDK Runtime Environment (21.0.4)**
Heap size: **144.3 MiB**, total JVM memory: **452.0 MiB**
Free memory: **307.7 MiB**, max memory: **4.0 GiB**
Free disk space: **97.6 GiB**, total disk space: **465.6 GiB**

### Steps To Reproduce

1. run artemis ci image
2. create queue with name b
3. run frank with h2 in mem, no transactionmanager, artemis driver and resource in context.xml
4. run attached config
5. put message on queue and see that message is gone and not returned

### Configuration

```xml
<Module
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://frankdoc.frankframework.org/xml/xsd/FrankConfig.xsd"
>
	<Adapter name="JMSTest">
		<Receiver>
			<JmsListener 
				destinationName="b" 
				lookupDestination="false" 
				queueConnectionFactoryName="jms/artemis"
				acknowledgeMode="client"
			/>
		</Receiver>
		<Pipeline>
			<EchoPipe name="echo"/>
			
			<ExceptionPipe name="oeps" />
		</Pipeline>
	</Adapter>
</Module>
```

### Input

<frank/>

### Anything else?

main point of this issue is to get the golden standard config for a jms adapter that process a message from the queue and properly returns the message on the queue when an exception occurs without transaction manager. Could be that attached config of the jmslistener is not complete/correct for this purpose.

**Comment by VBPham** [comment]
@tnleeuw What i currently expect from the attached config is that the message is tried twice. I am interpreting the default setting of the maxRetries="1" on the receiver to mean that it will retry the message one additional time after the initial try. Combined with the fact the client (frank) will never acknowledge that the message has been successfully processed in this config.

However the adapter status shows no rejection, only that it, inevitably, has failed:

![image](https://github.com/user-attachments/assets/994c66df-0e2c-48ca-af28-494bfe293019)

And the logging shows an acknowledgment after the first initial try and skips client acknowledge:

```txt
...
2024-09-12 14:33:49,638 DEBUG [JmsListener[1]] {adapter=JMSTest} jms.JmsListener - [listener of [JmsListener]] acknowledging message
...
2024-09-12 14:33:50,642 DEBUG [JmsListener[1]] {} jms.IbisMessageListenerContainer - Skip client acknowledge in commitIfNecessary()
```
full log

```txt
2024-09-12 14:33:49,569 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  received message with messageId [null] correlationId [null]
2024-09-12 14:33:49,570 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  Message without message id; generated messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,571 INFO  [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  did not find (technical) correlationId, reverting to messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,571 INFO  [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] correlationId [null] businessCorrelationId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,571 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  checking try count for messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,571 DEBUG [JmsListener[1]] {adapter=JMSTest} jms.JmsListener - determined delivery count [1]
2024-09-12 14:33:49,571 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  starts processing message
2024-09-12 14:33:49,571 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener] PipeLineSession variables for messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] correlationId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]: replyTo=[null] tsSent=[2024-09-12 14:33:49.566] tsReceived=[2024-09-12 14:33:49.569] __JmsSession=[ActiveMQSession->ClientSessionImpl [name=42864106-7103-11ef-9ad2-4ee546eb28e6, username=null, closed=false, factory = org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl@4e27c645, metaData=()]@40c82a56] timestamp=[2024-09-12T12:33:49.566Z] cid=[synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,571 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  preparing TimeoutGuard
2024-09-12 14:33:49,571 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  activating TimeoutGuard with transactionTimeout [0]s
2024-09-12 14:33:49,571 INFO  [JmsListener[1]] {adapter=JMSTest} core.Adapter - Adapter [JMSTest] received message with messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,629 DEBUG [JmsListener[1]] {adapter=JMSTest} processors.MonitoringPipeProcessor - Pipeline of adapter [JMSTest] messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] is about to call pipe [echo] current result (Message) [context:
Metadata.Name: null
Metadata.ModificationTime: 2024-09-12 14:33:49.566
JMSXDeliveryCount: 1
Metadata.Size: 5
value:
Message[2f3a1842:String]: [<r1/>]] 
2024-09-12 14:33:49,630 DEBUG [JmsListener[1]] {adapter=JMSTest} processors.MonitoringPipeProcessor - Pipeline of adapter [JMSTest] messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] is about to call pipe [oeps] current result (Message) [context:
Metadata.Name: null
Metadata.ModificationTime: 2024-09-12 14:33:49.566
JMSXDeliveryCount: 1
Metadata.Size: 5
value:
Message[2f3a1842:String]: [<r1/>]] 
2024-09-12 14:33:49,635 DEBUG [JmsListener[1]] {adapter=JMSTest} processors.TransactionAttributePipeLineProcessor - setting RollBackOnly for pipeline after catching exception
2024-09-12 14:33:49,635 WARN  [JmsListener[1]] {adapter=JMSTest} core.Adapter - Adapter [JMSTest] error processing message with messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]: Pipe [oeps] <r1/>
2024-09-12 14:33:49,635 DEBUG [JmsListener[1]] {adapter=JMSTest} core.Adapter - Adapter: [JMSTest] STAT: Pipeline finished processing message with messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] exit-state [ERROR] started 2024-09-12 14:33:49.571 finished 2024-09-12 14:33:49.635 total duration: 64 ms
2024-09-12 14:33:49,635 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  canceling TimeoutGuard, isInterrupted [false]
2024-09-12 14:33:49,635 ERROR [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener] Exception in message processing
org.frankframework.core.ListenerException: Pipe [oeps] <r1/>
	at org.frankframework.core.Adapter.processMessageWithExceptions(Adapter.java:614) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.frankframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1219) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.frankframework.receivers.Receiver.processRawMessage(Receiver.java:1093) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.frankframework.receivers.Receiver.processRawMessage(Receiver.java:1055) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.frankframework.unmanaged.SpringJmsConnector.onMessage(SpringJmsConnector.java:263) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:787) ~[spring-jms-6.1.12.jar:6.1.12]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:742) ~[spring-jms-6.1.12.jar:6.1.12]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:720) ~[spring-jms-6.1.12.jar:6.1.12]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:333) ~[spring-jms-6.1.12.jar:6.1.12]
	at org.frankframework.jms.IbisMessageListenerContainer.doReceiveAndExecute(IbisMessageListenerContainer.java:104) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:270) ~[spring-jms-6.1.12.jar:6.1.12]
	at org.frankframework.jms.IbisMessageListenerContainer.receiveAndExecute(IbisMessageListenerContainer.java:96) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1257) ~[spring-jms-6.1.12.jar:6.1.12]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1147) ~[spring-jms-6.1.12.jar:6.1.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.frankframework.core.PipeRunException: Pipe [oeps] <r1/>
	at org.frankframework.pipes.ExceptionPipe.doPipe(ExceptionPipe.java:52) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	... suppressed 15 lines
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:181) ~[frankframework-ladybug-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... suppressed 18 lines
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:154) ~[frankframework-ladybug-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... suppressed 15 lines
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... suppressed 6 lines
	at org.frankframework.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:119) ~[frankframework-ladybug-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	... suppressed 16 lines
	at org.frankframework.core.PipeLine.process(PipeLine.java:389) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	at org.frankframework.core.Adapter.processMessageWithExceptions(Adapter.java:606) ~[frankframework-core-8.3.0-20240906.042421.jar:8.3.0-20240906.042421]
	... 16 more
2024-09-12 14:33:49,637 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  caching first result for messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8]
2024-09-12 14:33:49,637 DEBUG [JmsListener[1]] {adapter=JMSTest} jms.JmsListener - [listener of [JmsListener]]  in JmsListener.afterMessageProcessed()
2024-09-12 14:33:49,637 INFO  [JmsListener[1]] {adapter=JMSTest} jms.JmsListener - [listener of [JmsListener]] no replyTo address found or not configured to use replyTo, and no sender, not sending the result.
2024-09-12 14:33:49,638 DEBUG [JmsListener[1]] {adapter=JMSTest} jms.JmsListener - [listener of [JmsListener]] acknowledging message
2024-09-12 14:33:49,638 DEBUG [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener]  finishes processing message
2024-09-12 14:33:49,639 DEBUG [JmsListener[1]] {adapter=JMSTest} jms.JmsListener - determined delivery count [1]
2024-09-12 14:33:49,639 INFO  [JmsListener[1]] {adapter=JMSTest} receivers.Receiver - Receiver [JmsListener] message with messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] has already been received [1] times; maxRetries=[1]; error in procesing: [Pipe [oeps] <r1/>], will continue retrieving messages in [1] seconds. Details: NA
2024-09-12 14:33:50,641 DEBUG [JmsListener[1]] {} core.PipeLineSession - Closing PipeLineSession
2024-09-12 14:33:50,642 DEBUG [JmsListener[1]] {} core.PipeLineSession - messageId [synthetic-message-id-7f000001-74da7176_191e61b67fe_-7ff8] auto closing resource [Message of TestTool]
2024-09-12 14:33:50,642 INFO  [JmsListener[1]] {} unmanaged.SpringJmsConnector - SpringJmsConnector of Receiver [JmsListener]  A) JMSMessageTime [2024-09-12 14:33:49.566]
2024-09-12 14:33:50,642 INFO  [JmsListener[1]] {} unmanaged.SpringJmsConnector - SpringJmsConnector of Receiver [JmsListener]  B) onMessageStart [2024-09-12 14:33:49.568] diff (~'queing' time) [2]
2024-09-12 14:33:50,642 INFO  [JmsListener[1]] {} unmanaged.SpringJmsConnector - SpringJmsConnector of Receiver [JmsListener]  C) onMessageEnd   [2024-09-12 14:33:50.642] diff (process time) [1074]
2024-09-12 14:33:50,642 DEBUG [JmsListener[1]] {} jms.IbisMessageListenerContainer - Skip client acknowledge in commitIfNecessary()
```

Maybe the exception pipe is not a true exception since it is explicitly configured. So in the frank's perspective the message has been properly processed and therefor acknowledged?

**Comment by tnleeuw** [comment]
I will look into it. Messages "put back on the queue" is basically: the message is rejected, and so the queue system retries it.

I need to look at the exact interpretation of "maxRetries" / "maxRedeliveries". It might be that there's an off-by-one error in this.

BTW, does your scenario work in an older version of the Frank!Framework, like 7.9 or 8.0?

**Comment by VBPham** [comment]
No, same behaviour in 7.9.4 and 8.0.3

**Comment by tnleeuw** [comment]
OK, I figured out what is happening 🤦 

In 7.8, messages with ackMode=client were always acknowledged, when received.

In 7.9, an attempt was made to improve this. Messages are only acknowledged when de `PipeLineResult.state != ERROR`.

However, when an exception occurred during the pipeline, no PipeLineResult is returned. The Receiver code creates one, sets the result to an error message, but never sets the state and so when the check is made to acknowledge the message or not, state = NULL, which is not ERROR, and thus the message is acknowledged and disappears...
