### ISSUE TITLE
RawMessageWrapper contains String instead of JCOFunction

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7588]
https://github.com/frankframework/frankframework/commit/6b4d02b93b58daa27193f2abd25479c958b2ef0d#diff-805f7f0d706788881a7fef8e168432a605206abe45e475139e81e8432c6c932cR194

```
2024-09-30 15:45:22,468 ERROR [JCoServerThread-3] {adapter=IncomingSAP} receivers.Receiver - Receiver [IncomingSAP] exception processing message, will continue processing messages when they arrive
nl.nn.adapterframework.core.ListenerException: (ClassCastException) java.lang.String incompatible with com.sap.conn.jco.JCoFunction
      at nl.nn.adapterframework.receivers.Receiver.wrapExceptionAsListenerException(Receiver.java:1858) [ibis-adapterframework-core-7.9.4.jar:7.9.4]
      at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1313) [ibis-adapterframework-core-7.9.4.jar:7.9.4]
      at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1045) [ibis-adapterframework-core-7.9.4.jar:7.9.4]
      at nl.nn.adapterframework.extensions.sap.jco3.SapListenerImpl.handleRequest(SapListenerImpl.java:194) [ibis-adapterframework-sap-7.9.4.jar:7.9.4]
      at com.sap.conn.idoc.jco.rt.GenericJCoIDocServerWorker$IDocDispatcher.handleRequest(GenericJCoIDocServerWorker.java:345) [sapidoc3.jar:20230225 0202 [3.1.3 (2023-01-02)]]
      at com.sap.conn.idoc.jco.rt.DefaultJCoIDocServerWorker$IDocDispatcherProxy.handleRequest(DefaultJCoIDocServerWorker.java:73) [sapidoc3.jar:20230225 0202 [3.1.3 (2023-01-02)]]
      at com.sap.conn.jco.rt.AbstractServerWorker.dispatchRequest(AbstractServerWorker.java:265) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.CPICServerWorker.dispatchRequest(CPICServerWorker.java:26) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerConnection.dispatchRequest(AbstractServerConnection.java:2073) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerConnection.executePlayback(AbstractServerConnection.java:1449) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerConnection.playbackTRfc(AbstractServerConnection.java:1323) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerConnection.handletRfcRequest(AbstractServerConnection.java:1480) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerConnection.dispatchProtocolFunction(AbstractServerConnection.java:1171) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerConnection.listen(AbstractServerConnection.java:946) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.CPICServerWorker.dispatch(CPICServerWorker.java:73) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerWorker.loop(AbstractServerWorker.java:372) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at com.sap.conn.jco.rt.AbstractServerWorker.run(AbstractServerWorker.java:336) [sapjco3.jar:20240615 0037 [3.1.10 (2024-06-14)]]
      at java.lang.Thread.run(Thread.java:825) [?:2.9 (03-05-2024)]
Caused by: java.lang.ClassCastException: java.lang.String incompatible with com.sap.conn.jco.JCoFunction
      at nl.nn.adapterframework.extensions.sap.jco3.SapListenerImpl.afterMessageProcessed(SapListenerImpl.java:165) ~[ibis-adapterframework-sap-7.9.4.jar:7.9.4]
      at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1304) ~[ibis-adapterframework-core-7.9.4.jar:7.9.4]
 
```

**Comment by evandongen** [comment]
PR's created for [8.0](https://github.com/frankframework/frankframework/pull/7610) and [8.3 (master)](https://github.com/frankframework/frankframework/pull/7611).
