### ISSUE TITLE
Bad dependency in ibis-xerces 2.12.2-xml-schema-1.1??

### ISSUE THREAD

**Issue by petrbizon** [frankframework/frankframework#8035]
### Current Behavior

When I use:
        <dependency>
            <groupId>org.ibissource</groupId>
            <artifactId>ibis-xerces</artifactId>
            <version>2.12.2-xml-schema-1.1</version>
        </dependency>
in my project. 

I get this error when I validate some xml:

Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.wst.xml.xpath2.processor.DefaultEvaluator.<init>(Lorg/eclipse/wst/xml/xpath2/processor/DynamicContext;Lorg/w3c/dom/Document;Lorg/w3c/dom/Node;)V
...

When I change my pom.xml in this way:

 <dependencies>
        <dependency>
            <groupId>org.ibissource</groupId>
            <artifactId>ibis-xerces</artifactId>
            <version>2.12.2-xml-schema-1.1</version>
            <exclusions>
                <exclusion>  
                    <groupId>com.rackspace.eclipse.webtools.sourceediting</groupId>
                    <artifactId>org.eclipse.wst.xml.xpath2.processor</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.wst.xml.xpath2</groupId>
            <artifactId>org.eclipse.wst.xml.xpath2.processor</artifactId>
            <version>1.2.0</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>Rackspace 3rd Party</id>
            <url>https://maven.research.rackspacecloud.com/content/repositories/third-party/</url>
        </repository>
    </repositories>

error disapeard.
It looks like your version of dependency org.eclipse.wst.xml.xpath2.processor in your pom.xml is not compatible with xerces. 

### Expected Behavior

Can you please make new version of this repository without 
org.eclipse.wst.xml.xpath2.processor dependency problem?

### Environment Information

windows 11
Java zulu8.72.0.17-ca-jdk8.0.382-win_x64

**Comment by nielsm5** [comment]
Strange we've been using this plugin for many years now. Could you create a junit test or share the bit of code that caused the beforementioned exception?

**Comment by petrbizon** [comment]
Try this please:

```
package main;


import org.xml.sax.SAXException;

import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;

public class Main {

    public static void main(String[] args) {
        //System.setProperty("java.net.useSystemProxies", "true");

        String xmlPath = "https://raw.githubusercontent.com/nithril/xml-schema-v1.1/refs/heads/master/xml/valid.xml";
        String xsdPath = "https://raw.githubusercontent.com/nithril/xml-schema-v1.1/refs/heads/master/xml/test.xsd";

        try {

            InputStream xml = new URL(xmlPath).openStream();
            InputStream xsd = new URL(xsdPath).openStream();

            SchemaFactory factory = SchemaFactory.newInstance("http://www.w3.org/XML/XMLSchema/v1.1");
            Schema schema = factory.newSchema(new StreamSource(xsd));
            Validator validator = schema.newValidator();
            validator.validate(new StreamSource(xml));

        } catch (SAXException e) {
            e.printStackTrace();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}

```

```

Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.wst.xml.xpath2.processor.DefaultEvaluator.<init>(Lorg/eclipse/wst/xml/xpath2/processor/DynamicContext;Lorg/w3c/dom/Document;Lorg/w3c/dom/Node;)V
	at org.apache.xerces.impl.xs.AbstractXPath2EngineImpl.evaluateXPathExpr(Unknown Source)
	at org.apache.xerces.impl.xs.XMLAssertXPath2EngineImpl.evaluateOneAssertion(Unknown Source)
	at org.apache.xerces.impl.xs.XMLAssertXPath2EngineImpl.evaluateAssertionsFromComplexType(Unknown Source)
	at org.apache.xerces.impl.xs.XMLAssertXPath2EngineImpl.processAllAssertionsOnElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLAssertXPath2EngineImpl.endElement(Unknown Source)
	at org.apache.xerces.impl.xs.XSDAssertionValidator.handleEndElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.assertionValidatorEndElementDelegate(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleEndElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source)
	at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at main.Main.main(Main.java:33)
```
